### ISSUE TITLE
TokenInput 组件接口

### ISSUE THREAD

**Issue by atoanofish** [ecomfe/veui#101]
属于输入组件 提供disabled readonly autofocus等功能。

# Props
<table>
  <thead>
        <tr >
            <th>prop</th>
            <th>type</th>
            <th>default</th>
            <th>desc</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>tokens</td>
            <td>Array</td>
            <td>空</td>
            <td>标签数组，对象数组。数组元素形式为{label:'',value:''}。</td>
        </tr>
        <tr>
            <td>value</td>
            <td>Array</td>
            <td>空</td>
            <td>标签value值数组。当tokens为空时，默认显示value数组</td>
        </tr>
        <tr>
            <td>triggerkey</td>
            <td>Array</td>
            <td>空</td>
            <td>triggerkey数组控制输入时以什么分隔符来决定插入一个token</td>
        </tr>
        <tr>
            <td>placeholder</td>
            <td>String</td>
            <td>空</td>
            <td></td>
        </tr>
        <tr>
            <td>validateToken</td>
            <td>Function</td>
            <td>空</td>
            <td>校验时候可以插入</td>
        </tr>
        </tbody>
    </table>

# Events
<table>
        <thead>
        <tr>
            <th>functionName</th>
            <th>args</th>
            <th>desc</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>input(value)</td>
            <td>value</td>
            <td>输入时触发.
                value:返回当前input 框中的value值
            </td>
        </tr>
        <tr>
            <td>select(value)</td>
            <td>value</td>
            <td>添加的value的token值</td>
        </tr>
        </tbody>
    </table>

**Comment by qbaty** [comment]
如果是一个input  应该要支持 v-model
Props 里应该是 value, 事件应该支持 $emit('input')
nameAttr 需要吗？这个应该可以要求固定的格式 [{label:'xxx', value: 'value1'}]
事件名称不需要加on
https://github.com/ecomfe/veui/wiki/%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

**Comment by Justineo** [comment]
名字改为 `TokenInput` 吧。

1. `delete` 不需要，输入控件必然可以删除啊……不然写错了怎么编辑。
2. `classes` 也是多余的，功能还不如在组件上直接写 `class`。
3. `partten` 是错误的拼写，`pattern` 也是不需要的，校验会在 `Field` 上面进行，看 Wiki 有说明。
4. `tagList` 应该拆分为 `tokens` 和 `value`。`tokens` 是一个 `{ label, value }` 对象的数组，`value` 是一个值的数组。这个逻辑其实和 `Select` 组件是一样的，可以参考一下。用到 `TokenInput` 的场景下，提交的数据不应该把 `label` 一起提交上去。另外 `tokens` 应该可选，比如输入多个 Email 地址的场景，可以直接在没有 `tokens` 配置时直接按 `value` 显示。
5. 缺 `v-model` 实现描述。
6. 缺 slots 设计，可以为每个 token 开放一个 scoped slot。
7. 事件名命名不符合规范，事件应该分为普通 `input`（正在进行文字输入）以及 `select`（确认某个 `token` 被添加，这个应该用来实现 `v-model`）。
8. `props` 里应该提供一个 `validateToken` 函数，来检验 `token` 是否能加入结果，去掉你 functions 里写的那些。
9. `props` 应该提供一个 `triggerKey` 配置，来表达输入时以什么分隔符来决定插入一个 token。
10. 拖拽排序可以有，建议叫 `sortable`，可以后期再加。
11. 插入功能我考虑实现起来可能稍微复杂一点，有 `sortable` 的话功能可以用来代替，也建议暂时不要实现。

**Comment by atoanofish** [comment]
好的 我在想想 我明天改完哈
