### ISSUE TITLE
ColorPicker 组件接口

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#102]
### Props

prop | type | default | desc
-----|------|--------|------
color | String |  #fff | 颜色，支持 v-model, .sync
ui | String | normal  | 展现形式，(small\|normal)[ (hex\|rgb\|hsl)[ alpha]]
readonly | Boolean | false | 文本框只读

```vue
<veui-color-swatch color="#ff00ff" ui="small hex alpha"></veui-color-swatch>
```

### Props

prop | type | default | desc
-----|------|--------|------
color | String |  #fff | 颜色，支持 hex, hsl(a), rgb(a)；v-model, .sync
ui | String | normal  | 展现形式，small: 小, normal: 中, large: 大
format | String | hsl | 输出颜色格式：hsl, rgb, hex；其中, hex 会丢弃 alpha 值，所以format: hex时无法修改alpha值。转换为rgb时会丢弃小数部分导致精度降低，不建议使用。

```vue
<veui-color-picker v-model="color" ui="normal"></veui-color-picker>
<veui-color-picker :color.sync="color" ui="large"></veui-color-picker>
```

### Events

name | args | desc
-----|--------|------
update:color | color | 颜色改变

### Props
prop | type | default | desc
-----|------|--------|------
colors | Array<String> |  [] | 颜色集
ui | String | normal  | 展现形式: small, normal

### Events

name | args | desc
-----|--------|------
select | index | 选择颜色
remove | index | 删除颜色
add | | 添加颜色

```vue
<veui-color-picker v-model="color">
  <veui-color-palette :colors="colors" ui="small"
    @select="handlePaletteColorSelect"
    @remove="handlePaletteColorRemove"
    @add="handlePaletteColorAdd"
  ></veui-color-palette>
</veui-color-picker>
```

**Comment by Justineo** [comment]
### `ColorSwatch`

尺寸预设几个 `ui`？定制的话用 CSS 吧？

### `ColorPicker`

这个应该属于输入控件吧，`v-model` 不需要 `update:color`，直接提供 `value` prop 好了。然后把 `select` 事件配成 `model.event` 就好。`ui` 描述是不是太非主流了……还有可以透传 `ColorPalette` 的参数吧？

**Comment by 599316527** [comment]
ColorSwatch 预设尺寸可以

ColorPicker 因为目前用 update:color 是为了能支持 .sync，同时也作为 model.event 支持 v-model

透传 ColorPalette 参数是什么意思？
