### ISSUE TITLE
tabs组件截断时增加tooltip

### ISSUE THREAD

**Issue by markfan** [ecomfe/veui#1052]
### 版本信息

```sh
veui版本2.7.0
```

### 问题详情

tabs组件超宽时会自动截断，导致标签页文本无法完全展示，希望增加tooltip显示标签页文本

### 问题复现

https://codepen.io/Justineo/pen/yLbxxOR

**Comment by Justineo** [comment]
Issue template 都搞好了，选对模板不难吧……如果要照 bug report 来提，那问题复现就不要填一个空的模板路径进来。
