### ISSUE TITLE
Loading组件的loading区域可否覆盖到default slot

### ISSUE THREAD

**Issue by liuniansilence** [ecomfe/veui#1071]
### 新功能详情

参考Ant design的Spin组件，觉得Spin组件的交互很舒服，普通情况下Spin组件有tip属性作为提示文字。
但是当Spin组件有子节点的话，Loading会覆盖全部子节点，比如Table的加载的时候，
```
<Spin :loading="isLoading">
    <Table />
</Spin>
```
附一下antd的spin组件链接：https://ant.design/components/spin-cn/#components-spin-demo-tip
如果整个表格上层被覆盖一个loading区域，觉得交互上会舒服很多。

或者像Element-UI的loading 是提供了一个loading的directive，效果也是在整个组件的节点上覆盖一层loading。
附ElementUI的loading组件效果：https://element.eleme.cn/#/zh-CN/component/loading#qu-yu-jia-zai

现有的veui Loading组件的只是一个loading icon和文字部分分割成左右或者上下两部分的。

**Comment by Justineo** [comment]
这恐怕是不行的，因为 `default` slot 的语义目前就是文字提示部分的内容，修改这个会是一个 breaking change。另外 Antd 这种设计其实会让 Spinner 在 DOM 中产生一层 wrapper，对内部元素的定位或者样式产生影响。我们希望使用者用更加显式的方式去进行布局，比如给每一个可能产生加载状态的容器自己写一个自己更加可控的 wrapper。当然如果希望用 Antd 这种接口，其实也可以自己简单封装一下。

**Comment by liuniansilence** [comment]
> 这恐怕是不行的，因为 `default` slot 的语义目前就是文字提示部分的内容，修改这个会是一个 breaking change。另外 Antd 这种设计其实会让 Spinner 在 DOM 中产生一层 wrapper，对内部元素的定位或者样式产生影响。我们希望使用者用更加显式的方式去进行布局，比如给每一个可能产生加载状态的容器自己写一个自己更加可控的 wrapper。当然如果希望用 Antd 这种接口，其实也可以自己简单封装一下。

如果antd的实现会造成veui组件的breaking change，那么directive的实现方案呢，绑定指令的时候侵入式的在组件宿主节点里append一个mask的节点。这样也不会改变原有组件的wrapper。

**Comment by Justineo** [comment]
往未知内容的容器里面插入一个元素本身是一个很不可控的行为，里面的元素如果有针对 `:last-child` 这样的选择器写了样式，就会产生错乱了。只有使用者自己写 wrapper 自己控制样式才是安全的。
