### ISSUE TITLE
Form组件setValidities加进去的error在修改组件值后没了

### ISSUE THREAD

**Issue by liuniansilence** [ecomfe/veui#1094]
### 版本信息

```sh
veui@2.8.2
```

### 问题详情

通过setValidities塞进去某个field A的错误信息，我不手动清除这个error，只是改动了A的值，之前塞进去的error信息也没了

### 问题复现

https://codesandbox.io/s/nk6c6d?file=/src/Demo.vue

**Comment by Justineo** [comment]
线下沟通，确认符合预期。
