### ISSUE TITLE
日历筛选组件-月份筛选年份高亮与选中不一致

### ISSUE THREAD

**Issue by dingzhenyue** [ecomfe/veui#1101]
### 版本信息

```sh
veui@2.1.0
```

### 问题详情

calendar组件type为month时，选中的年份与高亮年份不一致，目前看上去高亮的年份一直是今年？请问是特意做成这样的吗？

### 问题复现

https://veui.dev/components/calendar

**Comment by Justineo** [comment]
按目前的设计，高亮（蓝色文字）都是和当前日期相关的。
