### ISSUE TITLE
TagInput 删除输入中的拼音时会触发已有 tag 的删除

### ISSUE THREAD

**Issue by tumars** [ecomfe/veui#1133]
### 版本信息

```sh
vue@2.6.12
veui@2.13.2
```

### 问题详情

![2023-03-24 19 32 11](https://user-images.githubusercontent.com/9925509/227510498-80aedf2a-1f2b-4fcb-893f-9385802da084.gif)

如图所示，删除在输入中的拼音时，会误触发 input 内 tag 的删除。

### 问题复现

无

**Comment by Justineo** [comment]
Fixed by com/ecomfe/veui/commit/eab8fdbe061144.
