### ISSUE TITLE
TagInput 内删除 tag 时，会将所有的相同 tag 同步删除

### ISSUE THREAD

**Issue by tumars** [ecomfe/veui#1135]
### 版本信息

```sh
vue@2.6.12
veui@2.13.3
```

### 问题详情

![2023-03-28 15 08 55](https://user-images.githubusercontent.com/9925509/228156451-08e99c3e-4570-45f2-965d-f1941ad65814.gif)
如上图所示，allow-duplicate 模式下删除 tag 时，会将所有的相同 tag 同步删除。

### 问题复现

无

**Comment by Justineo** [comment]
Fixed in v2.13.4.
