### ISSUE TITLE
实时编辑器有开源吗

### ISSUE THREAD

**Issue by rudyxu1102** [ecomfe/veui#1151]
官网的实时编辑器挺好用，请问这个有开源吗

**Comment by Justineo** [comment]
https://github.com/ecomfe/veui-docs/blob/master/components/OneLive.vue

主要依赖：

* vue-live
* vue-monaco
* splitpanes

**Comment by Justineo** [comment]
补充一下，有部分依赖有 patch：https://github.com/ecomfe/veui-docs/tree/master/patched
