### ISSUE TITLE
Transfer 组件接口

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#118]
[草稿]

### Props

* `datasource`: `Array`

  ```js
  [
    {
      id: '1',
      label: 'Steve Rogers'
    },
    {
      id: '2',
      label: 'Natasha Romanov'
    },
    ...
  ]
  ```

* `searchable`: `Boolean`

* `filter`: `Function`

* `selected`: `Array` [`v-model`]

### Events

* `select` [`v-model`]

### Slots

* `default`

* `candidate-label`

* `selected-label`

### Scoped Slots

* `canditate-item`

* `selected-item`

**Comment by yibuyisheng** [comment]
### Props

* `datasource`: `Array`

  ```js
  [
    {
      value: '1',
      label: 'Steve Rogers'
    },
    {
      value: '2',
      label: 'Natasha Romanov',
      children: [
        {
          value: '3',
          label: 'Bruce Banner'
        }
      ]
    },
    ...
  ]
  ```

* `searchable`: `Boolean`

* `filter`: `Function`

* `selected`: `Array` [`v-model`]

* `candidatePlaceholder`: `String` 备选列表中 Searchbox 里面的 placeholder 文本

* `selectedPlaceholder`: `String` 已选列表中 Searchbox 里面的 placeholder 文本

* `selectedShowMode`: `'TREE' | 'FLAT'` 已选列表展示已选项的方式。`TREE` 代表展示得像一棵树一样；`FLAT` 意思是扁平展示。默认展示为 `TREE`。

### Events

* `select` [`v-model`]

### Slots

* `candidate-title`

![image](https://user-images.githubusercontent.com/2581682/31490661-4f362c06-af0a-11e7-842f-6c4bf54afc02.png)

* `candidate-no-data`

![image](https://user-images.githubusercontent.com/2581682/31490603-2b67bd9e-af0a-11e7-910d-dca310a696de.png)

* `selected-title`

![image](https://user-images.githubusercontent.com/2581682/31491334-985d8012-af0c-11e7-85e4-91e933fc6e73.png)

* `selected-no-data`

![image](https://user-images.githubusercontent.com/2581682/31491354-a9ad4f5a-af0c-11e7-8fde-061977d319cd.png)

### Scoped Slots

* `canditate-item`

![image](https://user-images.githubusercontent.com/2581682/31491721-d4f0823a-af0d-11e7-96fb-226260ff8604.png)

* `candidate-item-label`

![image](https://user-images.githubusercontent.com/2581682/31491698-c1b586fc-af0d-11e7-9d31-32ffa19a9991.png)

* `candidate-item-right`

![image](https://user-images.githubusercontent.com/2581682/31491676-b5bd3f8e-af0d-11e7-9807-e0d839ff28c2.png)

* `candidate-expand-icon`

![image](https://user-images.githubusercontent.com/2581682/31491651-a114561c-af0d-11e7-96df-bed1930b0861.png)

* `selected-item`

![image](https://user-images.githubusercontent.com/2581682/31491546-560eb3f6-af0d-11e7-927e-57e65cdff5b3.png)

* `selected-item-label`： 仅在 `selectedShowMode='TREE'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491603-885bad5a-af0d-11e7-9fc9-cccfe1d3bd2a.png)

* `selected-item-right`： 仅在 `selectedShowMode='TREE'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491592-79d52144-af0d-11e7-8e8b-314472d4d711.png)

* `selected-expand-icon`： 仅在 `selectedShowMode='TREE'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491521-40a5ad9e-af0d-11e7-81bd-612d86009dfb.png)

* `selected-flat-item-option-label`： 仅在 `selectedShowMode='FLAT'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491485-19db3bac-af0d-11e7-8f25-f9c1a1d1e58a.png)

* `selected-flat-item-option-separator`： 仅在 `selectedShowMode='FLAT'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491452-fc068c62-af0c-11e7-8199-f8ae5a9508c6.png)

* `selected-flat-item-right`： 仅在 `selectedShowMode='FLAT'` 的时候有效。

![image](https://user-images.githubusercontent.com/2581682/31491426-e1972670-af0c-11e7-9a46-4e4c2916723a.png)

**Comment by Justineo** [comment]
* 图标不需要开 scoped slot，全部删掉。
* 枚举值用小写，HTML 不区分大小写，都用小写。比如：`autocomplete="off"`。

**Comment by yibuyisheng** [comment]
### Props

* `datasource`: `Array`

  ```js
  [
    {
      value: '1',
      label: 'Steve Rogers'
    },
    {
      value: '2',
      label: 'Natasha Romanov',
      children: [
        {
          value: '3',
          label: 'Bruce Banner'
        }
      ]
    },
    ...
  ]
  ```

* `searchable`: `Boolean`

* `filter`: `Function`

* `selected`: `Array` [`v-model`]

* `candidatePlaceholder`: `String` 备选列表中 Searchbox 里面的 placeholder 文本

* `selectedPlaceholder`: `String` 已选列表中 Searchbox 里面的 placeholder 文本

* `selectedShowMode`: `'tree' | 'flat'` 已选列表展示已选项的方式。`TREE` 代表展示得像一棵树一样；`FLAT` 意思是扁平展示。默认展示为 `TREE`。

### Events

* `select` [`v-model`]

### Slots

* `candidate-title`

* `candidate-no-data`

* `candidate-head`

* `selected-title`

* `selected-no-data`

* `selected-head`

### Scoped Slots

* `canditate-item`

* `candidate-item-label`

* `candidate-item-right`

* `selected-item`

* `selected-item-label`： 仅在 `selectedShowMode='tree'` 的时候有效。

* `selected-item-right`： 仅在 `selectedShowMode='tree'` 的时候有效。

* `selected-flat-item`： 仅在 `selectedShowMode='flat'` 的时候有效。

* `selected-flat-item-option-label`： 仅在 `selectedShowMode='flat'` 的时候有效。

* `selected-flat-item-option-separator`： 仅在 `selectedShowMode='flat'` 的时候有效。

* `selected-flat-item-right`： 仅在 `selectedShowMode='flat'` 的时候有效。

**Comment by Justineo** [comment]
Scoped slots 里面的 `*-right`、`*-flat-*`、`*-option-*` 我理解都不需要啊。

**Comment by Justineo** [comment]
一个 Transfer 不可能既 flat 又不 flat 吧，所以可以用同一个 scoped slot，传不同的默认内容。
