### ISSUE TITLE
Table 组件支持展开行

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#119]
如题。

**Comment by AlbertAZ1992** [comment]
同时 Table 组件能否再提供 row slot、 暴露出 table-row组件 ？现在只有column slot，如果点击或hover 整行时触发需求，且需求比较复杂，处理起来都不是很方便。

**Comment by Justineo** [comment]
@AlbertAZ1992 不开放出来是因为后面如果要做固定列之类的功能，整行如果是外部定义的就不好处理了呀。而且行的内容还会受 `selectable` 和展开功能影响，自定义的话是否能和原来的功能一同工作就很难保证了。如果是需要点击整行的事件，倒是可以增加一个事件抛出来的。

**Comment by Justineo** [comment]
See #208.
