### ISSUE TITLE
Calendar 接口

### ISSUE THREAD

**Issue by Phinome** [ecomfe/veui#14]
## props

| Prop          | Type         | Default     | Description                         |
|---------------|--------------|-------------|-------------------------------------|
| value         | String  |             | datepicker 值       |
| name          | String       |             |   form 提交时 name                |
| readonly            | Boolean       |    false         |     是否只可读              |
| placeholder   | String       |             | input placeholder text              |
| disabled | Boolean | false| input disabled attr |
| range | Object | |  预设时间范围快捷选择 |
| inputFormat        | String       | yyyy-MM-dd | 输入日期格式  年 yyyy，月 MM，日 dd |
| outputFormat        | String       |  yyyy-MM-dd | 输出日期格式 年 yyyy，月 MM，日 dd|
| inline        | Boolean      |    false       | 总是展示  |
| ui   | String       |             |  calendar ui 样式|
| clearable   | Boolean     | false       | 是否可清除 |
| disabledDates| Function| | 不可选择的时间       |

## Range Object

```javascript
function addDays(days) {
  let current = new Date();
  return current.setDate(current.getDate() + days);
}

const current = new Date();
enum ShortDayRange {
    weekday,
    weekend
}
const range: {
        from: current,
        to: addDays(7),
        exclude: [Date/String/ShortDayRange]
    }
```

## disabledDates

```javascript

function disabledDate(current) {
  // can not select days before today and today
  return current && current.valueOf() < Date.now();
}

<veui-datepicker :disabledDates="disabledDate"></veui-datepicker>

```

## Events

- change
- click

**Comment by Justineo** [comment]
之前不是说，DatePicker 和 Calendar 分开么？DatePicker 是一个输入控件，包含一个输入框和一个下拉浮层，Calendar 是其中展示的日历。

`language` 暂时不需要吧，即使需要也不会以组件为粒度去设置吧。

为什么会有 `id`？为什么要分 `input-ui` 和 `wrapper-ui` 呢？

怎么设置哪些日期不可选？

输入控件没有 `readonly` 和 `disabled`吗？

事件参考原生命名，不需要用过去式吧。

我觉得你应该再好好参考一下其他组件库提供的属性/事件。

**Comment by chestnutchen** [comment]
`value`/`name`/`disabled`部分属性`InputControl`会`mixin` 进去的，不过最好每个组件也写上，实现的时候直接引`mixin`就是
