### ISSUE TITLE
Select 相关新增需求

### ISSUE THREAD

**Issue by atoanofish** [ecomfe/veui#143]
1 希望能够自定义select组件中 overlay的overlayClass
2希望增加事件（点击option）可以反回当前item 对象。
3 如果能有文档 || 源码 || demo 中能加入组件”参数“配置的注释就更好了

**Comment by Justineo** [comment]
- [ ] 增加 mixin `overlay`，由所有与单一浮层逻辑的组件引入。

  `props` 中提供 `overlayClass`，最终会设置到 `Overlay` 容器 `class` 上。

- [ ] `Select` 在选择完成时额外抛出 `select` 事件，带出来自 `options` 的完整对象。

文档是未来长期工作，目前 UE 还没给出官网设计，应该倒时会一起发布。

**Comment by AlbertAZ1992** [comment]
希望 `Select` 支持搜索，或者支持配置是否内置 `Searchbox`，可能是长期需求了。

**Comment by chestnutchen** [comment]
@AlbertAZ1992 这个需求实现过几个，正在梳理成标准的
