### ISSUE TITLE
Slider组件接口

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui#146]
Slider（部分内容待完善）

## props
prop | type  | default | desc 
------------ | ------------- | ------------- | -------------
min | Number | 1 | 最小有效value
max | Number  | 100 | 最大有效value
value | Number | 64 | 此范围的当前值
snapInterval | Number | 1 | 控制 value 属性的有效值。如果为非零，则有效值为 min 与此属性的整数倍数之和，且小于或等于 max
vertical | Boolean | false | 是否垂直显示组件
tipShow | Boolean | true | 如果设置为 true，则在用户交互期间将显示包含滑块当前值的数据提示。
tipFormat | Function | null | 格式化数据提示文本的回调函数。此函数使用单个 Number 作为参数并返回格式化的 String。
tipPrecision | Number | 0 | 用于数据提示文本的小数位数。值 0 表示将所有值舍入为整数。如果已定义 tipFormat，则会忽略此值
liveDragging | Boolean | false | 如果为 true，则将在沿着轨道拖动滑块时，而不是在释放滑块按钮时，提交此滑块的值。
ui | String | '' | _**内容待补充**_

`code待添加`

## event
name | args | desc
 ------------ | ------------- | -------------
update:value | value | 组件当前的有效value

## 设计思路，以默认水平方向滑块轨道说明（_*以下内容待完善*_）
1.百分比value值
2.百分比width值

两种轨迹思路
1.全部的轨道，包含滑块在内，对应滑块的圆心轨迹，在轨道上
2.除滑块以外的宽度，对应滑块的左侧边缘轨迹在轨道上

对应HTML结构设计
1.待完善
2.待完善

**Comment by Justineo** [comment]
Slider 应该实现输入组件的 mixin。

DOM 上的状态需要感知 `realDisabled` / `realReadonly` 两个 computed 值。

## Props

* `snapInterval`

  `step` 更加妥当吧。

* `range`

  范围选择（暂时不用实现）。

* `tipShow` / `tipFormat` / `tipPrecision`

  删除，用 scoped slot `tip` 代替。

* `liveDragging`

  感觉命名不直观，感觉没有必要，而且本地值和 prop 值还会产生不同步。

## Events

* `update:value` &rarr; `input`

  支持 `v-model`。

浮层显示的内容可以完全由 scoped slot 来指定，是显示值还是百分比都可以外部指定。Scoped slot 里可以预先计算一些值方便调用。

**Comment by 599316527** [comment]
实现细节讨论结论：
1. 组件宽度自适应，滑块宽度自适应。dragstart 时读取尺寸，drag 时计算并转化为百分比
2. 组件宽度即为 track 宽度（对齐 input 组件），thumb 可溢出。
3. 提示显示动效使用统一的 transition name 机制
4. 考虑到：①垂直方向 track、thumb 可能不是单纯的水平方向的转90°，组件内需要做复杂的处理；②组件使用时需要为不同的 ui 类型传入不同的 slot 以满足垂直滑块的需求；③垂直滑块的需求完全可以使用水平滑块实现；因此暂不实现垂直 ui.

**Comment by 599316527** [comment]
看了 Polymer [pager-slider](https://www.webcomponents.org/element/PolymerElements/paper-slider) 的实现，它还有个 secondary-progress 的选项，对应 pager-progress，组合起来我想到的使用场景是在用作播放器的进度条，同时有播放进度和缓冲进度

**Comment by 599316527** [comment]
这个东西的 ARIA 咋弄？

**Comment by Justineo** [comment]
单个的：https://www.w3.org/TR/html-aria/#index-aria-slider
