### ISSUE TITLE
InputControl 实现规范

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/veui#15]
InputControl 实现规范

`InputControl`**必须**要实现的公开属性：
1. **value**，组件初始化及输出的格式化数据
2. **name**，组件数据输出名称
3. **readonly**，只读状态
4. **disabled**，禁用状态
5. **uiTypes**，描述组件的类型

`InputControl`**必须**要实现的私有属性：
1. **_rawValue**，组件内部处理时使用的结构化数据

`InputControl`**必须**要实现的公开方法：
1. **serialize**，提供给外部比如`Form`序列化表单数据使用的方法

`InputControl`**必须**要实现的私有方法：
1. **_convert**，从组件`value`转化为`_rawValue`的内部方法

以上属性由`mixins/input.js`提供声明及部分默认定义，创建`InputControl`需要`mixin`该模块，并对部分需要增强自身逻辑的属性及方法进行覆盖。具体接口实现请关注 #10

**Comment by otakustay** [comment]
1. 不觉得这个时代的webapp的input还应该分value和rawValue，我觉得应该只有rawValue
2. 同样不觉得input应该自己管serialize

**Comment by chestnutchen** [comment]
灰大说的我们也考虑过，我保留的想法主要是
1. 后端存储的时候还是字符串格式为主，类似日期范围 `20170401-20170407`，所以前端拿到数据进行初始化的时候，是免不了又一次`parse`的，只是在业务逻辑里边做，还是组件提供格式化标准，这里我选择放在组件里边是为了减少业务层面的重复`parse`。
2. 组件内部交互产生的数据，肯定是操作很频繁的，如果没有`rawValue`，每次使用都要`parse`不显示，那么相当于只能让业务层去`parse`成结构化数据传递给组件，所以`rawValue`是必须存在的，这点大家都没有意见。
3. `serialize`这个还在讨论，回答的意思是`Form`直接接管吗？我是考虑到如果存在两个组件，结构化数据相同，但是提交的时候想序列化成不同格式，这个还是有存在必要的，不过这种场景可能比较少。

**Comment by chestnutchen** [comment]
我提到的3的情况，比如对于 `rawValue` 同样是 `Object` 的组件，有的输出 `JSON.stringify(Object)` ，有的是 `xxxx-xxxx`。
其实对于 `value` 和 `rawValue` 的问题，我想到的是两种方案
1. 保留两者，提供`serialize`
2. 统一 `rawValue` 就是`serialized`的数据，业务想用啥格式自己`parse`，组件内部想用啥格式也自己`parse`

我觉得2写起来比较烦...灰大觉得呢

**Comment by otakustay** [comment]
我说几个事实，你参考一下：

1. 一个信息通过字符串能表达的内容远远小于这个信息的原本类型
2. 因此在一个自闭合（即不和外部交互）的逻辑内部，使用原始类型传递信息远比使用字符串来得强大和便捷
3. 对于一个合理的应用架构，序列化永远是越晚越好，反序列化永远是越早越好，很多应用架构把序列化和反序列作为传输层的一部分，以保证一切以序列化结束，以反序列化开始
4. 序列化本身是一个可以通用化的逻辑，其输入是对象输出是字符串，反序列化同理
5. 序列化实现的不同是因为数据类型的不同，而不是组件类型的不同
6. 不同类型的应用会使用不同形式的序列化实现，并不由组件决定

你如果是一个合格的前端app，理应在各组件之间、组件和业务逻辑之间传递的都是强类型的信息，只有组件内部直接使用原生DOM时因为`HTMLInputElement`只提供value的限制才会有将字符串变为其它类型的parse操作才对，而这点parse应该仅存于最最基本的一系列InputControl中，基本上就是input的一个type对应一个组件，除此之外除非和后端交互，就不该有更多的parser和serialize操作了

因此我觉得你所谓的serialize和parse要到处使用是不应该出现的情况，而“对于 rawValue 同样是 Object 的组件，有的输出 JSON.stringify(Object) ，有的是 xxxx-xxxx”这种事情应该是应用架构中涉及前后端接口交互的部分（传输层？）来统一做的事，和你的业务逻辑并不存在关系

**Comment by chestnutchen** [comment]
明白了，重新设计下
