### ISSUE TITLE
Tree 组件接口

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/veui#170]
### Props

* `datasource`: `Array`

```js
[
  {
    value: '1',
    label: 'Steve Rogers'
  },
  {
    value: '2',
    label: 'Natasha Romanov',
    children: [
      {
        value: '3',
        label: 'Bruce Banner'
      }
    ]
  },
  ...
]
```

* `itemClick`: `'toggle' | 'none'`

### Events

* `click`

* `expand`

* `collapse`

### Scoped Slots

* `item`

* `item-label`

**Comment by Justineo** [comment]
为啥偏移量要用 JS 计算呢？把节点嵌套渲染不行么。

**Comment by yibuyisheng** [comment]
我想实现这种 hover 效果：

![image](https://user-images.githubusercontent.com/2581682/31597650-2f18c50c-b20f-11e7-9283-c219a8eabb3b.png)

**Comment by Justineo** [comment]
搞个 `::after` 伪元素垫在下边？

**Comment by yibuyisheng** [comment]
用 `::after` 的话，好像也要知道每一层 item 的左偏移量？

**Comment by Justineo** [comment]
可以这样啊：

```less
.item {
  .absolute(_, 0);
}
```

**Comment by yibuyisheng** [comment]
我理解 `::after` 是用来做后面那个灰块的，为了让这个灰块占整个一条，要设置当前 item 宽度充满整个容器，然后 `item::after` 再充满这个 item 块。

但是还要确定一下 item 的内容区域偏离 item 块左侧的距离：

![image](https://user-images.githubusercontent.com/2581682/31601018-12637e52-b21e-11e7-9e2a-c6389ba70acc.png)
