### ISSUE TITLE
优化各组件的多 prop 联合校验

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/veui#178]
`Select`、`BoxGroup` 等包含 `options`/`datasource` 的组件，`value` 同步时需要在其中过滤。

**Comment by Justineo** [comment]
我理解其实这个可以泛化一下，需要进一步支持组件的多个 prop 的联合校验。目前应该是只支持在 `created` hook 里面自己去干这个事情。

**Comment by Justineo** [comment]
好了，我修改了一下。
