### ISSUE TITLE
Tooltip 动态设置 target 可能失败

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/veui#187]
`target` 指定为 ref 字符串的时候，`targetNode` 使用 `computed` 会阻止后续重新计算。

**Comment by yibuyisheng** [comment]
Tooltip 内部无法感知 target 指代的“外部 DOM 结构”变化，所以无法及时更新与 targetNode 相关的各个变量（realOpen 、 outsideOptions 等），看起来只能依靠使用者自己解决了（通过直接传递 DOM node 的方式）。

**Comment by Justineo** [comment]
以后用文档详述用法吧。
