### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/veui#19]
# props
| Prop | Type | Default | Description |
| ----- | ----- | ---------| --------------|
| ui   | String |		| 全局 ui 属性  |
| type | String | text  | 可选 password，默认 text |
| name | String | 		| 绑定到标签 name 属性 |
| placeholder | String | | 绑定到标签 placeholder 属性，ie9 内部实现 |
| value | String, Number | | 绑定到标签 value 属性 |
| readonly | Boolean | false | 只读状态，绑定到标签 readonly 属性 |
| disabled | Boolean | false | 禁用状态，绑定到标签 disabled 属性 |
| autofocus | Boolean | false | 自动聚焦，绑定到标签 autofocus 属性 | 
| autocomplete | String | off | 可选 on，默认 off，原生补全，绑定到标签 autocomplete 属性 |  
| selectOnFocus | Boolean | false | 聚焦时自动全选 |
| composition | Boolean | false | 感知输入法组合态 |  
| fitContent | Boolean | false | textarea 模式是否随行数调整大小 |
| resizable   | Boolean | false | textarea 模式能否调整大小 |
| rows  | Number |  | textarea 模式行数 |  

## Events
 - **focus** `<event>`
 - **click** `<event>`
 - **blur** `<event>`
 - **change** `<value, event>`
 - **input** `<value, event>`

## usage
```html
<veui-input ui="small" 
    v-model="password"
    type="password"
    composition
    select-on-focus
    fit-content
    autofocus
    placeholder="请输入密码"
    @click="log('click')"></veui-input>

**Comment by Justineo** [comment]
`ignorecomposition` 是不是应该反过来？就是需要感知输入法的，写 `<veui-input composition></veui-input>`？否则必须得写 `<veui-input :ignorecomposition="false"></veui-input>` 了。

你上面的例子：

```
<veui-input ui="small" v-model="password" type="password" placeholder="请输入密码"
    autoselect autofocus @click="log('click')"></veui-input>
```

事件还是有 `input` 的吧？还有是否考虑 `<textarea>`？

**Comment by chestnutchen** [comment]
`textarea`貌似是另一个组件？根节点只能有一个吧，不能`v-if`就没法玩

**Comment by otakustay** [comment]
顺便提一点，我觉得input和change还是应该是2个东西……

**Comment by chestnutchen** [comment]
`input`内部拿去实现`v-model`了。。。

**Comment by Justineo** [comment]
> 现在默认是true，改成false?

是把意义改过来，而不是默认值……
