### ISSUE TITLE
select/Option增加 option item级别的slot

### ISSUE THREAD

**Issue by teazean** [ecomfe/veui#195]
目前 select/Option的slot只能算是 slot[name=label]，计划再增加一个 option/item级别的默认slot。

但是发现一个问题，也是之前讨论过的：

在select/Select使用select/Option是，好像是只能往外开放select/Option的默认slot；如果select/Option有slot[name=default]和slot[name=label]这样的话，按照目前的设计，就永远也不能达到 ui=checkmark下，只覆盖label的情况。

```
<veui-option
            v-else
            v-bind="option"
            :ui="ui"
            :selected="option.value === value"
            :key="option.value"
            @select="handleSelect(option)">
            <slot name="option" v-bind="option" :selected="option.value === value"></slot>
</veui-option>

```

**Comment by teazean** [comment]
想重新设计select/Option,增加select/OptionCheckmarkView，类似于一下结构。

```
<div class="veui-select-option">
    <!-- 其他逻辑 -->
    <div v-if="ui.contains('checkmark')">
        <veui-option-checkmark-view><slot></slot></veui-option-checkmark-view>
    </div>
    <div v-else>
        <slot>{{label}}</slot>
    </slot>
</div>
```

还没去测试这样通过v-if设置两个默认slot是否可行。。

**Comment by Justineo** [comment]
这样过于复杂了吧……我理解你 option 里整个包一层，然后 label 外面包一层，给两个 scoped slot 差不多了。

**Comment by teazean** [comment]
但是在select/Select里面只能开放 select/Option的一个slot[name=default]，做不了同时开放 select/Option的两个slot吧(slot[name=default]、slot[name=label])
