### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/veui#2]
# BreadcrumbItem

## props

* separator 节点分隔符
* to 要跳转到的链接

## events

* click

## slots

```
<veui-breadcrumb-item to="http://www.baidu.com">首页</veui-breadcrumb-item>
```

# Breadcrumb

## props

 * separator 节点分隔符

## events

* item-click 会传递给回调函数`$index`参数

## slots

示例：

```html
<veui-breadcrumb @item-click="onBreadcrumbItemClick($index)">
    <veui-breadcrumb-item :to="'http://www.baidu.com'">首页</veui-breadcrumb-item>
    <veui-breadcrumb-item>用户列表</veui-breadcrumb-item>
</veui-breadcrumb>
```

to 和 item-click 互斥，to 的优先级更高。

**Comment by Justineo** [comment]
考虑一下和 vue-router 如何协同工作吧，是否能在引入或不引入 vue-router 时都能有比较合适的行为。使用场景的示例再丰富一点，到时候作为 demo/test case。
