### ISSUE TITLE
ButtonGroup

### ISSUE THREAD

**Issue by neverlandcx** [ecomfe/veui#20]
# props
prop | type | default | description |
------------ | ------------- | ------------- | ------------- |
name | String | -- | 控件名 |
ui | String | -- | 选填，样式的变种 |
current | Number | 0 | 选填，默认选中的索引 |
vertical | String | false | 选填，是否垂直排列 |
items | Array | -- | 必填，text/value的配置 |

# events
click

# usage
``` javascript
<veui-button-group :items="items3" :current="current" :vertical="vertical"></veui-button-group>

```

**Comment by otakustay** [comment]
为啥不是一个slot能接受若干个button呢……现在如果要button上有icon之类的复杂样式会不会比较难搞了

**Comment by Justineo** [comment]
@neverlandcx

1. 缺少 slots 的说明；
2. `ButtonGroup` 为啥会有 `current` 呢？
3. `item` 里边的 `value` 是指啥？有什么用呢？

**Comment by otakustay** [comment]
另外，Group有没有内部按钮互斥或者不互斥的配置呢？互斥的时候其实是一个SegmentControl？

**Comment by Justineo** [comment]
UE 对这个组件的设计描述好像很不完整。@neverlandcx 再找 UE 确认一下吧。这个组件到底是作为类似 RadioBoxGroup 的存在（Segment），还是只是单纯地把 Button 做分组，在什么场景下使用。

**Comment by qbaty** [comment]
这个ButtonGroup 感觉都和Tab 有点像了
