### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by neverlandcx** [ecomfe/veui#21]
# props
props | type | defalut | description
------------ | ------------- | ------------ | -------------
ui | String | -- | 样式的变种small/large/~~plain~~
name | String | -- | 组件名
state | String | off | 开关状态: on/off/loading
disabled | Boolean | false | 禁用
readonly | Boolean | false | 只读
~~errorMessage~~ | String | -- | 错误信息
~~animate~~ | Boolean | true | 是否带动画效果

# events
click/change

# usage
<veui-toggle-button ui="small plain" :state="state" onText="开" offText="关">
</veui-toggle-button>

**Comment by Justineo** [comment]
这个组件长啥样的？

**Comment by neverlandcx** [comment]
UE图按钮中的开关样式。

**Comment by Justineo** [comment]
开关样式应该叫做 Switch？

**Comment by Justineo** [comment]
- `animate`：这个我理解不需要设置？应该是 UE 规范到时候统一处理的。
- `state`：这个和 `value` 不是冗余了么？
- `errorMessage`：这个后面看 `Form` 是否统一处理吧。

**Comment by neverlandcx** [comment]
删掉了这几个

**Comment by otakustay** [comment]
Switch是没有on和off的text的所以这东西不能叫Switch

value和state是啥关系？如果这东西本质和checkbox类似的话，是不是value应该是any？

**Comment by otakustay** [comment]
另外如果切换的过程涉及异步的逻辑的话，这个组件还应该有一个loading状态的控制

**Comment by neverlandcx** [comment]
这个按钮点了以后是立即执行操作的，所以应该不需要value.

**Comment by otakustay** [comment]
那就是Switch了，但是Switch不应该有text，开关时表达两个完全互斥的状态的，不需要文字说明状态是啥

**Comment by Justineo** [comment]
@otakustay 

我已经给 UE 建议把文字删掉了，这个很容易产生误导。

反正这玩意儿就是一个即使触发数据变更的 Checkbox。不过如果我们设计上作 Optimistic UI 的假设的话，就不需要 loading 状态了。
