### ISSUE TITLE
更新到新版图标

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#230]
One 标局的图标和 `veui-theme-one/icons` 中的图标是对不上的，包括命名和样式。

如果直接更新到新版的话，项目中如果有直接引用 `veui-theme-one/icons/*`，那么如果该图标被改名或删除，将导致 breaking change。

有一个保证兼容的方案：

* 发布 `veui-theme-one-icons`，把新图标发布到这里；
* `veui-theme-one/icons` 保留，保持兼容；
* `veui-theme-one` 内部使用的图标更新，全部指向 `veui-theme-one-icons`。

---

@599316527 @chestnutchen @yibuyisheng @teazean 

看看有没有更好的建议？

**Comment by teazean** [comment]
看 One 标局，UE 也有很强的意愿维护更新一套，强烈支持：`veui-theme-one-icons`。

在项目中使用 `veui-theme-one/icons/*`，猜想就是为了保持 icon 类型、风格一致。所以要保持兼容性的时候，希望能把 `veui-theme-one/icons/*` 引用到新的 `veui-theme-one-icons` 里。

**Comment by 599316527** [comment]
没啥建议。图标能丰富一些吗，现在一堆相似的图标，但真正需要的图标缺了很多

**Comment by Justineo** [comment]
@599316527 veui-theme-one 用到的肯定也就商业系统的那些，编辑器要用的话感觉其实还是不太合适的。可以跟商业 UE 沟通一下看看有没有可能一起支持。没人设计的话可能得引第三方资源了。

**Comment by thirtyjin** [comment]
UE 这边的图标一直在扩容，数量也在增加，可以找机会合并一批进来，这边的中英文命名也都维护整理。现在有353左右。

**Comment by Justineo** [comment]
@thirtyjin 把组件标注里的图标改成新版的之后我们就可以开始切换了。

**Comment by Justineo** [comment]
Done.
