### ISSUE TITLE
v-numeric 指令功能

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#240]
v-numeric 用于数字类输入组件的指令，提供功能：

## 支持键盘方向键调整(加、减)数值

参数可以配置:

- step: 继承组件的 step（如果有），默认值：1
- bigStep: 大步进值，一般交互上按 shift + 方向键，默认值：10倍step值
- smallStep: 小步进值，一般交互上按 option + 方向键，默认值：0.1倍step值
- min: 继承组件 min 属性
- max: 继承组件 max 属性

对于 Input 组件，在输入框内按上下方向键调整；对于 Slider 组件，聚焦 thumb 的情况下按左右方向键调整。调整时不能超出 min/max 范围。

## 支持格式化显示

预定义格式有：

- 无：没有格式化
- 精度：部分组件(如Slider)的value值过长，需要缩短长度
- 时长：把时长 秒 转换为 时分秒 形式显示 （200秒 → 3分20秒）

用户也可以指定 parse 和 format 自行实现。

--------------

没有想清楚的地方：

是否在同一个指令上实现这两个功能？像 drag 那样通过 handler 来扩展功能？
键盘方向键调整通过 keydown 事件触发，格式化通过 change 事件触发；先调用 keydown 回调，parse -> process -> format ；再调用 change 回调重复一遍？还是说要把两个处理过程合并起来，流程想不清楚。
键盘输入、方向键调整、鼠标拖动、外部 setValue 等行为导致值的变换时的格式化（限定上下限、步进、精度等）是否都可以统一用 format 实现。

另外一个对于 Input 格式化显示的问题。假如存在 `duration=200` ，我希望显示的是 `03:20`，但值还是 200 ，那么 Input 是不是就得增加 displayValue 来应对？（对应 `value = parse(displayValue)`, `displayValue = format(value)`）
也就是说存在两种情况：① format 产出的值就是组件 value，② format 产出的值是用于显示的值，value 还是 value

**Comment by Justineo** [comment]
格式化和 numeric 似乎没有什么直接的关系吧。我觉得这个是另一个维度的事情，相当于要给 input 类型的组件提供一个 alternate input，给真实值再加一层双向绑定。

**Comment by 599316527** [comment]
那好，只实现第一个点


GU Yiling <notifications@github.com>于2018年2月25日 周日00:57写道：

**Comment by 599316527** [comment]
想的是 v-numeric 应用于 Input Component 及其子节点 和 Input Element 上，自动修改 value 值。但实现上发现找 vnode 改 value 有点 [复杂](https://github.com/ecomfe/veui/pull/238/commits/cf2acb306698173877fa0ccf70c0b55962e9994d#diff-edbc95b786c1ed19789454e52658a6e4R48)，对于特殊格式的值不够通用。所以改成了传 [回调函数](https://github.com/ecomfe/veui/pull/238/files#diff-edbc95b786c1ed19789454e52658a6e4R90) 的方式

**Comment by Justineo** [comment]
我也觉得必须外部自己处理回调，比如 numeric 调整的步进值和 Slider 的步进值不一定相同，可大可小也可能不是整数倍，这就麻烦了。不同组件逻辑都可能不同，所以还是让组件自己来实现吧。

**Comment by Justineo** [comment]
Implemented as `v-nudge`.

**Comment by 599316527** [comment]
补全用法：v-nudge
axis: x | y，按左右/上下箭头调整
step: 默认 1，按住 option 调整时 *0.1，按住 shift 调整时 *10
update: 修改回调

具体的组件 value怎么改，组件自己在回调函数里实现
