### ISSUE TITLE
看源码，好像Select组件的clearable属性没用

### ISSUE THREAD

**Issue by asd123freedom** [ecomfe/veui#241]
例子中的clearable属性为true并没有显示出清除按钮，源码当中好像并没有做处理

**Comment by Justineo** [comment]
`clearable` 的 `Select` 第一个选项会是 `placeholder`，选这一项就会使其恢复未选状态。

**Comment by yibuyisheng** [comment]
`clearable` 的作用是控制“是否把 placeholder 放置在下拉选项中”。

有这样一种常见场景：
<img width="200" src="https://user-images.githubusercontent.com/2581682/36779824-3653b78e-1cac-11e8-81fe-de89ccdb30cc.png">

其中，`全部`选项是一个很特殊的选项，可以通过 placeholder 和 clearable 来设置：

```html
<veui-select placeholder="全部" clearable ...></veui-select>
```

如果 `clearable` 为 `false` （默认值），下拉选项中就不会出现`全部`了。

这里的 `clearable` 含义就是“选择了某一非特殊项之后，是否能够清空 `Select` 组件值”。

**Comment by asd123freedom** [comment]
哦。。原来是这样，和DatePicker的clearable弄混了。。。
