### ISSUE TITLE
关于 priority of field validate rule 的升级讨论

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/veui#245]
目前 validate rule 的 `priority` 存在 `unstable` 的问题，比如：
> `numeric` 和 `pattern`，优先级是一样的，校验顺序和错误消息的显示通过 `Array.sort` 对预设的 `priority` 进行排序，相同时就依赖 `Array.sort` 的实现了。但是其实从功能上来看，`numeric` 是 `pattern` 的一种特殊场景，应该优先检查。

目前的改造方案：
1. 提高 `numeric` 的优先级或者降低 `pattern` 的优先级。
2. `rule` 增加一个 `priority` 的属性，可以覆盖默认规则的 `priority`，仅在当前 `Field.rules` 的校验中生效。
3. 增加对 `Field.rules` 的顺序感知，依赖这个顺序做优先级执行和错误消息的显示。 - **Breaking change**
4. 在 3 的基础上，扩展 `Rule`，增加 `Field.ruleMode`，指明优先级依赖，去除 Breaking change。

@Justineo @yibuyisheng  @599316527

**Comment by teazean** [comment]
> 但是其实从功能上来看，numeric 是 pattern 的一种特殊场景，应该优先检查。

不应该在添加 validate rules 的时候，事先排好序么？比如 [numeric, pattern]

**Comment by chestnutchen** [comment]
@teazean 就是看优先级来排的，目前这两个规则优先级一样。

**Comment by teazean** [comment]
好吧，已经有了 priority 的设置，感觉优先级的分级、维护也挺蛋疼的。

**Comment by yibuyisheng** [comment]
作为使用者，应该是很清楚 rule 的顺序和错误消息的优先显示顺序。
而开发者，对这个顺序倒是知道的很模糊。

所以，这个顺序应该主要交给使用者来确定，而开发者最多只需要提供少许的排序信息（ priority ）。

对于列举的 4 点改造，只做第 4 点就行了（第 4 点包含了第 3 点）。有了第 4 点支持，第 2 点似乎也没必要实现了。

**Comment by Justineo** [comment]
现在的实现中，规则类型上有优先级，而不是规则实例。给某个输入组件定义规则实例时没有定义优先级的接口。规则优先级总的来说应该是越特殊的越晚检查。如例子中的 `numeric` 和 `pattern`，一般来说同时使用的场景是用 `numeric` 给出基本格式，再用 `pattern` 做更精细的定制处理。所以总的来说 `pattern` 优先级应该更低一些。

**Comment by chestnutchen** [comment]
@Justineo 目前的设计应该是，规则的管理和计算逻辑是一个类的实例，每个规则是一个单例，按照2的做法，可以考虑把规则也抽成类，计算时根据传入配置实例化。

@yibuyisheng 4 是在 3 的基础上增加的，3 是独立功能，4 不是。完全交给使用者去决定这个顺序我觉得不现实，因为添加规则的时候有可能无意识就在数组最后添加，内置优先级的话，可以避免这种情况，也符合大多数场景，基本不需要覆盖优先级。后续我们给使用者提供优先级的文档，设置一个门槛来实现覆盖比较保险。所以我还是倾向于做 1 和 2。
