### ISSUE TITLE
Searchbox 支持输入为空的情况下，显示推荐列表

### ISSUE THREAD

**Issue by teazean** [ecomfe/veui#248]

**Comment by Justineo** [comment]
考虑新增 prop：`overlay-trigger`，可选 `submit`/`focus`/`input`。

**Comment by teazean** [comment]
现在 overlay 的显示隐藏是由外部监听 `input` or `search` 事件来设置 `suggestions` 控制显示隐藏，只是有一些内置行为：
1. `v-outside:input` 的时候隐藏 `overlay`
2.  空值情况下隐藏 `overlay`
3.  `input focusin` 下不会去触发 `overalay`

要支持这个 issue 的话，感觉要增加一个 `suggest` 的事件，之后统一在 `suggest` 事件中更新 `suggestions`，使用者根据 `suggest` 回调的 `value` 来控制是否设置 `suggestions`。为向后兼容，`input` 和 `search` 的事件继续保留。

按照这样设计的话：
![image](https://user-images.githubusercontent.com/4465253/37386895-56379126-2795-11e8-93cc-82c46be69da5.png)

这里定义: `input` 为输入框组件；`self` 为整个 `SearchBox` 组件。
想设计 2 个 prop 来控制这 2 种行为：
| prop | 类型 | 默认 | 解释 | 其他 |
| -- | -- | -- | -- |
| `suggest-trigger` | `input|action` | `input` | `input` 是指输入时触发；`action` 是指按`搜索/清空`按钮时触发  | `input` 情况下，`v-outside:input` 为自动隐藏 `overlay`；`action` 情况下， `v-outside:self` 会自动隐藏 `overlay` |
| `suggest-trigger-on-focus` | `boolean` | `false` | `input focusin` 情况下是否触发 `suggest` |  |

**Comment by Justineo** [comment]
能不能这样呢：

<table>
<tr><th>Prop</th><th>Type</th><th>Enum</th><th>Default</th></tr>
<tr>
    <td rowspan="2"><code>suggest-trigger</code></td>
    <td><code>string</code></td>
    <td><code>focus</code> / <code>input</code> / <code>submit</code></td>
    <td rowspan="2"><code>submit</code></td>
</tr>
<tr>
    <td><code>Array&lt;string&gt;</code></td>
    <td><code>string</code> 类型枚举值的数组</td>
</tr>
</table>

**Comment by teazean** [comment]
只有一个属性的话，可能会存在一些问题：
1. 正常来说，`input` 情况下，当点击搜索按钮的时候，一般都是表单提交，这个时候会期望 `overlay` 隐藏；而 `submit` 情况下，当点击搜索按钮的时候，一般都是请求 `suggestions`，这个时候期望 `overlay` 显示。所以 `input` 和 `submit` 感觉是有冲突的。
2. 单独的 `focus` 场景其实不存在，不能要求用户先 `blur` 再 `focus`。。

那这么看来，如果只有一个 prop 的话，真正的值只有四种：
- `input`
- `submit`
- `focus`, `input`
- `focus`, `submit`

**Comment by teazean** [comment]
其实场景就是：
1. focus/input 提交前查询内容，提交按钮不是用来查询的
2. submit 提交按钮就是用来查询的，提交后查看结果

这里 focus 是包含 input 的状态。

**Comment by teazean** [comment]
临时存放：
`suggest-trigger` 为枚举值，值可能为：
- `input`：只有输入框触发 `input` 事件时，才会触发 `suggest` 事件
- `focus`：当输入框处于 `focus` 的状态，任何变动都会触发 `suggest`，包含：
     - 输入框获取焦点
     - 输入框触发 `input` 事件
- `submit`：当点击『搜索』时触发 `suggest` 事件

**Comment by teazean** [comment]
第三种场景：
3. input/focus/submit 均是提交建议。。
