### ISSUE TITLE
在Select组件使用tether时候的配置问题

### ISSUE THREAD

**Issue by asd123freedom** [ecomfe/veui#256]
在源码中，Select组件使用的dropdown的mixin里面对tether的配置项如下
```
constraints: [
          {
            to: 'scrollParent',
            attachment: 'together'
          },
          {
            to: 'window',
            attachment: 'together'
          }
   ]
````

想问一下为什么要多一个scrollParent的配置，感觉这里是不是只有一个window就够了？

**Comment by Justineo** [comment]
如果目标元素在一个可滚动的容器内，加上 `scrollParent` 的话，可以使其在移出容器的时候翻转浮层吧。

**Comment by asd123freedom** [comment]
实际使用的时候我的感觉是这样的，下拉菜单本身已经被attach到了body上面，很多时候对菜单的期望就是不要超过window就行，而且在看了scrollParent的实现之后，感觉在实践当中会遇到问题，tether查找scrollparent的时候是顺着parentNode这个关系找没有设置过overflow属性的元素，我在实际当中遇到过的情况是，父元素设置了position:absolute，top, left, bottom, right全部设置为0，这样父元素被撑开了，但是这时候被选定为scrollparent的，是body，高度还是0。这种情况下，就会出现意料之外的下拉菜单的翻转。

**Comment by Justineo** [comment]
的确有点问题，下个版本删掉 `scrollParent`。谢谢反馈。
