### ISSUE TITLE
显式描述预设 ui 的元数据

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#257]
## 解决的问题

1. 合法性检查

    通过描述互斥性，使 `large small` 的写法自动报错；

2. 透传问题

    通过描述继承性，让某些 `ui` 值自动透传给下层，比如 `small`；

3. 允许为不同 `ui` 配置不同的图标。

## 升级方案

1. 将 `icons` mixin 合并入 `ui`；
2. 为每个组件都引入 `ui` mixin；
3. 改造组件的 `ui` 字段输出，不再依赖 `inheritAttrs`；
4. 在主题包中为每个组件增加 `ui` 属性的配置。

## 元数据格式

```js
{
  size: {
    values: ['large', 'small', 'tiny', 'micro'], // 枚举值
    inherit: true // 是否透传给子组件
  },
  shape: {
    values: ['square', 'round'],
    inherit: false
  },
  style: {
    values: ['primary', 'alt'],
    inherit: true,
    data: {
      // 附加的配置数据
      icons: {
        primary: {
          loading: 'loading-icon'
        }
      }
    }
  }
}
```

**Comment by teazean** [comment]
这个是咋校验的？

**Comment by Justineo** [comment]
根据配置的 `ui` 元数据，每一项是一个组，代表一个属性，值都是互斥的。

**Comment by chestnutchen** [comment]
这个可以解决 `ui` <-> `icon` 的问题，但是如果样式设计需要不同的模板结构，还是会耦合在模板中？

**Comment by Justineo** [comment]
不可能把所有东西都解耦出去。

**Comment by Justineo** [comment]
Implemented via #259.
