### ISSUE TITLE
Tabs 接口

### ISSUE THREAD

**Issue by qbaty** [ecomfe/veui#27]
# Tabs

# props
prop | type | default | description |
------------ | ------------- | ------------- | ------------- |
name | String | -- | 控件名 |
ui | String | -- | 选填，样式的变种 |
active | String | -- | 选填，默认没有激活 |
tabPosition | String | top | tabs的位置，有上下左右 |

## events
change

## slots
``` javascript
<veui-tabs active="1" @change="changed" tabPosition="left">
     <veui-tab-panel name="1" label="Tab one">This is Tab one content</veui-tab-panel>
     <veui-tab-panel name="2" label="Tab two">This is Tab two content</veui-tab-panel>
     <veui-tab-panel name="3" label="Tab three">This is Tab three content</veui-tab-panel>
</veui-tabs>
```

**Comment by Justineo** [comment]
`key` 是 Vue 的保留字，给 VDOM 节点打标记用的，不能用作 `props`。
建议 TabPanel 还是用 `label` + `name` 的组合吧。
Tab 上的 `active` 不适合用 `v-model` 来绑定，可以作为触发 `.sync` 的属性，变化时触发 `update:active` 事件来搞，等 Vue 下个版本就可以直接 :active.sync="tabIndex" 了。（感觉还可以支持 `Number` / `String` 两种值类型，分别对应 Tab 项的次序和 `name`，这样 `name` 就是一个可选属性了）

动效以后再统一考虑？
