### ISSUE TITLE
NumberInput 组件接口

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/veui#270]
## 实现方案
内部使用 `Input`，增减按钮使用 `Input` 的 `after` slot 来填充实现 

## Props
| Prop | Type | Default | Description |
| ----- | ----- | ---------| --------------|
| ui   | String |		| 全局 ui 属性  |
| name | String | 		| 绑定到标签 name 属性 |
| value | Number | | 绑定到标签 value 属性 |
| readonly | Boolean | false | 只读状态，绑定到标签 readonly 属性 |
| disabled | Boolean | false | 禁用状态，绑定到标签 disabled 属性 |
| step | Number | 1 | 使用方向键 `↑`/`↓` 来 `增加`/`减少` 时的原子数 |
| fixed-digits | Number | 0 | 精确到小数点后几位 |

## Events
 - **focus** `<event>`
 - **click** `<event>`
 - **blur** `<event>`
 - **change** `<value, event>`
 - **input** `<value, event>`

## Slots
- before
    - 对应到 `Input` 的 `before` slot
- after
    - 填充到 `Input` 的 `after` slot 中，处于增删按钮之后

## Usage
```html
<veui-number-input
  select-on-focus
  autofocus
  ui="small" 
  v-model="value"
  :step="0.1"
  :fixed-digits="2"
  placeholder="请输入价格"
  @click="log('click')"
>
  <span v-if="before" slot="before">￥</span>
  <span v-else slot="after">元</span>
</veui-number-input>

**Comment by chestnutchen** [comment]
`prop.nudge` 貌似也可以定义成输入 `Number`，直接映射到 `step` 值上边去

**Comment by Justineo** [comment]
`before` 可以对应到 `Input` 的 `before`，但是 `after` 不对应吧？我理解 `after` 应该是在加减按钮后面的吧。

**Comment by Justineo** [comment]
`readonly` 和 `disabled` 也是 mixin 的吧。

**Comment by chestnutchen** [comment]
@Justineo 
![image](https://user-images.githubusercontent.com/2787987/38076374-0464201a-3368-11e8-9a99-2137e9c8b512.png)

有说明啊
继承的那部分不是 mixin 的
