### ISSUE TITLE
Select组件重写uiTypes导致autoSubmit失效

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/veui#273]
https://github.com/ecomfe/veui/blob/dev/packages/veui/src/components/Select/Select.vue#L19

这里写上`uiTypes:['select']` 后会导致`autoSubmit`无法识别出它是`input`，导致无法绑定事件

**Comment by Justineo** [comment]
alpha.10 里修复了，要不等我晚上发个版？

**Comment by feibinyang** [comment]
好的

**Comment by Justineo** [comment]
`+veui@1.0.0-alpha.10`
