### ISSUE TITLE
select组件的下拉框，会导致滚动条错位

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui#290]
复现步骤：
前提条件，Select所在的页面存在滚动条。
1.点击select组件，显示出下拉选项。
2.滚动滚动条至select的Button被遮挡。
3.任意位置，点击鼠标。会导致滚动条回到Select的位置。

可能描述的不太准确，详见压缩文件。
[select.zip](https://github.com/ecomfe/veui/files/1927935/select.zip)
（tip:不支持mp4格式上传，辛苦解压一下，后续争取gif格式）

**Comment by Justineo** [comment]
现在浮层打开时会记录最后一个 focus 的元素，在浮层关闭时重新 focus 回去。这里的问题在于，下拉框展开后，把下拉框按钮滚动到可视范围外，点击空白处触发关闭后，重新 focus 到按钮时发生了滚动。

Chrome 64 开始支持了 `focus` 方法参数 `{ preventScroll: true }`，但是其它浏览器目前还没有支持。

可能需要考虑一下，如果是 pointer 事件触发的浮层关闭，似乎不需要 return focus 了。

**Comment by Justineo** [comment]
Fixed in #292.
