### ISSUE TITLE
checkbox组件，change事件不是每次都触发

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui#291]
demo:
![image](https://user-images.githubusercontent.com/29879262/38990205-e39efea4-440b-11e8-933e-f06195b43d9d.png)

console:
![image](https://user-images.githubusercontent.com/29879262/38990184-d1605c1a-440b-11e8-98ab-ebd0f750bb5a.png)

**Comment by Justineo** [comment]
`RegionPicker` 等一些组件依赖了这个逻辑，还是退回去了。

在这种情况下，没理由不使用 `v-model` 吧？
