### ISSUE TITLE
Code names

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#297]
`1.0.0` 正式发布后，我们可以选一个 code name 系列来在提升二位版本号时使用。在这里大家可以给些建议，欢迎大家给赞同的方案点赞。

可供参考的：

* Vue

  动漫名称，首字母从 A 开始依次往后排

* Element

  + 1.0：元素周期表
  + 2.0：碳元素及其构成的各种物质

* Ant Design

  没有版本 code name

* iView

  解谜游戏名称

**Comment by fuchunhui** [comment]
历史朝代，二十四节气感觉不错，但可能不够国际化

**Comment by 599316527** [comment]
词牌名，搞得跟我厂会议室一样 😂

**Comment by teazean** [comment]
dota2 heros name 😆

**Comment by teazean** [comment]
够国际化！有铁粉！

**Comment by Justineo** [comment]
提一个，咖啡的种类，比如：

* Mocha
* Latte
* Espresso
* ...

**Comment by Jinjiang** [comment]
球迷路过冒个泡：可以考虑用足球明星的名字：）

**Comment by 599316527** [comment]
用熊科、狼科动物的名字..

**Comment by Justineo** [comment]
> 熊科

![image](https://user-images.githubusercontent.com/1726061/39580883-c8c05076-4f1c-11e8-92fc-9495c4bf4966.png)

有点少，不可持续发展……

**Comment by teazean** [comment]
再提议一个，绝对用不完~『emoji 中 food & drink 的 shortname』
https://unicode.org/emoji/charts/full-emoji-list.html#food_&_drink

**Comment by Justineo** [comment]
We are using emojis as code names.

- 2.0.0 "📅 Calendar"
