### ISSUE TITLE
Select 组件后面待解决的一些问题

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#33]
- [x] 选项默认颜色不对

- [x] 右侧有图标时文字右边距太小

- [x] 缺少灰底样式

- [ ] 缺少分隔线

- [ ] Demo 缺少禁用、只读样式

- [ ] 缺前置样式

- [x] 下拉框高度是否可以指定？（须和 UE 确认）

- [ ] 下拉框边缘似乎有淡出效果

**Comment by feibinyang** [comment]
- [ ] 下拉框高度是否可以指定？（须和 UE 确认）
-- 这个之前和UE周文宁确认过的，我再确认一次。
- [ ] 下拉框边缘似乎有淡出效果
-- 这个之前说是Overlay统一做shadow效果？还是说淡出效果是指显示动画？

**Comment by Justineo** [comment]
> 选项默认颜色不对

下拉菜单展开后的文字颜色不对。

> 缺前置样式

我看视觉稿里面是有这个的？给个 `ui` 对应的样式？

**Comment by Justineo** [comment]
合并到 #59。
