### ISSUE TITLE
overlay 增加个性化class需求

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui#343]
需求点：每个overlay的弹层都包含统一的自定义的class名称，比如hulk-overlay。
class="veui-overlay-box hulk-overlay xxxx xxxx"

为什么有这种诉求？

目前的overlay的使用方式，在独自完整的项目中是不存在任何问题的。

我们有自己的皮肤库，veui-theme-blue，已经在多个项目中使用。
在hulk项目中，有些许和veui-theme-blue差别的点，因此我们在body上增加了class="hulk"，然后在通过
![image](https://user-images.githubusercontent.com/29879262/42375474-3ff823f4-814e-11e8-9e8f-8f5e03e5ef87.png)
这样的引用方式，可以覆盖所有内容，包含body下面直接的子veui-overlay-box。

------------------------------------------------------------
hulk可以单独作为sdk，供其他产品使用，其中有些项目也在使用veui
![image](https://user-images.githubusercontent.com/29879262/42375667-e26b88b0-814e-11e8-84de-620b35c022f5.png)
在引用hulk的产品上，我们只能把class="hulk"增加到div上，不能放到body上，这样的话，body下面的所有veui-overlay-box就没办法使用第一张图上设置的这些覆盖样式！！！

所以我们有这样的想法，希望overlay可以增加个性化的class设置。

**Comment by Justineo** [comment]
`1.0.0-alpha.15` 会增加全局配置项 `overlay.overlayClass`，可以配置所有浮层容器上的 `class`，支持的写法为所有 Vue 支持的 `class` 写法（`string|Array<string>|Object<string, boolean>`）。
