### ISSUE TITLE
svgson-next

### ISSUE THREAD

**Issue by elrumordelaluz** [ecomfe/veui#350]
Since [here](https://github.com/ecomfe/veui/blob/dev/packages/veui-theme-one/build/svg2json.js) this library is using `svgo` and `svgson` separately I am curious if [svgson-next](https://github.com/elrumordelaluz/svgson-next) (asap will be the next major version of `svgson`) could fit.

Benefits:
- Doesn't have `svgo` inside package
- Drop package size ([svgson-next@4.1.5](https://bundlephobia.com/result?p=svgson-next@4.1.5) 9.4kB vs [svgson@2.1.1](https://bundlephobia.com/result?p=svgson@2.1.1) 118.1kB)
- Promises ftw

Let me know if there are doubts, questions or want a PR.

**Comment by Justineo** [comment]
Hi, thanks. I don't see SVG optimization features in svgson-next so I'm wondering how can it replace SVGO here?

**Comment by elrumordelaluz** [comment]
In a similar way you are using right now, since you are making optimizations [outside svgson](https://github.com/ecomfe/veui/blob/dev/packages/veui-theme-one/build/svg2json.js#L24)

Take a look [here](https://github.com/elrumordelaluz/svgson-next/blob/master/test.js#L198-L216) where made the optimizations before pass into `svgson`.

Let me know if I misunderstand some thing.

**Comment by Justineo** [comment]
I see. You mean svgson is using svgo internally and svgson-next removed the dependency. Totally got it.

We'll update to the new version after it's released. Thanks for your work!

**Comment by elrumordelaluz** [comment]
awesome, let me know in any case.

**Comment by Justineo** [comment]
Updated to `svgson@3` via #387.
