### ISSUE TITLE
为什么一直提示我This dependency was not found:  * veui-theme-one/common.less in ./src/main.js  To install it, you can run: npm install --save veui-theme-one/common.less

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [ecomfe/veui#354]
已经安装veui-theme-one，我在main.js里面引入common.less文件，为什么提示我找不到

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
![image](https://user-images.githubusercontent.com/33676254/44068590-5daadaae-9fad-11e8-99c7-4cd0aaddccca.png)

**Comment by Justineo** [comment]
最新版的 VEUI 现在提供了一个 preset，你可以先尝试一下按这里的方式引入：https://github.com/ecomfe/veui/tree/dev/packages/babel-preset-veui

（不再需要自己引入其它插件）

`veui-theme-one/common.less` 找不到从你的错误信息看不出原因，你是怎么安装的呢？（npm/Yarn/cnpm/...?）
