### ISSUE TITLE
样式问题汇总

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#355]
- [x] `Dialog` 目前写死了 `400px` 的宽度，需要重新调整
- [x] `Progress` 尺寸目前不方便自适应

**Comment by 599316527** [comment]
Progress 尺寸问题，进度条写死了 `250px` 宽度，希望能优化成自适应宽度

https://github.com/ecomfe/veui/blob/dd0648deb0324e3bf8fc65b12f8e48f80de13037/packages/veui-theme-one/components/progress.less#L12-L18

**Comment by yibuyisheng** [comment]
@Justineo Dialog 宽度是要搞成哪种效果呢？

**Comment by yibuyisheng** [comment]
噢，好像搞好了，是根据 size 变化？

**Comment by Justineo** [comment]
@yibuyisheng 加了几个预设的 `ui`。

**Comment by dsonet** [comment]
目前的grid system貌似未支持responsive layout?

**Comment by Justineo** [comment]
@dsonet 是的，ONE DESIGN 的设计里面目前没有响应式布局。
