### ISSUE TITLE
Progress组件拆分为进度条和进度环两个单独组件的建议

### ISSUE THREAD

**Issue by sqliang** [ecomfe/veui#370]
目前 veui 的 Progress 组件通过 type 区分bar和circle，提供了展示操作进度的能力。但是，进度环除了可以用来显示操作进度的百分比，也可以用来展示某些统计指标的占比。因此，进度环可以添加一些比进度条更具广泛使用的特性。 
基于上面的思路，如果Progress继续封装成一个通过type来区分进度条和进度环的组件，会出现一些进度环可用而进度条不可用的属性，整体条理性不太好。因此，提出Progress组件拆分成进度条（Bar）和进度环（Circle）两个单独组件的建议，同时为进度环组件增加更广泛的属性，使其即可以用来展示操作进度，也可以当做简单的图表来使用，展示某些统计指标的占比。

**Comment by Justineo** [comment]
进度条也可以用来显示占比啊……

另外 Progress 的意思就是进度，如果有其它的需求可以基于此再封装专用的组件。目前有什么需求会导致两种类型的视图需要不一样的处理呢？

**Comment by Justineo** [comment]
VEUI 暴露线宽设置目前是通过主题包注入的。主要是不太希望暴露样式强相关的 prop。当然，直接暴露 prop 的确简单粗暴。

**Comment by sqliang** [comment]
> VEUI 暴露线宽设置目前是通过主题包注入的。主要是不太希望暴露样式强相关的 prop。当然，直接暴露 prop 的确简单粗暴。

嗯嗯，了解了，后面我这边看下，争取保持一致
