### ISSUE TITLE
翻页组件对外API设计疑惑

### ISSUE THREAD

**Issue by sqliang** [ecomfe/veui#377]
目前情况：
1、veui的分页组件采用to，native属性传入跳转（路由或原生跳转）的方式对外提供API，用户在使用的时候需要在模板里拼接to对应的值。

2、市场上以及原来的san-mui，是通过对外暴露change事件来供用户按照自己的意愿操作，组件内部自动跳转到选择的页码。

疑惑是：veui在设计之初，出于什么考虑选择了存在的对外API方式呢？就目前调研和日常写业务时用的习惯觉得第二种方式对外API更加精简，也给用户提供了更多自己设置的可能。

**Comment by Justineo** [comment]
我们希望分页应该都是链接。不过目前似乎没有覆盖掉的逻辑，可以考虑改进一下。

**Comment by sqliang** [comment]
> 我们希望分页应该都是链接。不过目前似乎没有覆盖掉的逻辑，可以考虑改进一下。

嗯嗯，现在这种方式要想翻页功能完备to属性是必须要传的，如果不传to属性，redirect事件也拿不到回调参数。我还是觉得以前用原生或者jquery写翻页时使用链接跳转比较方便。如果用vue或san这样的框架，对外暴露事件更合适，用户可以选择使用router或原生链接跳转，但也有不使用链接跳转的应用场景存在，所以翻页不一定都是链接，to可以作为不必要的补充属性，页码改变时对外的事件比to属性适用范围广。

![image](https://user-images.githubusercontent.com/6252409/48527113-f36c5f80-e8c4-11e8-8cb0-2caa0e24c137.png)
![image](https://user-images.githubusercontent.com/6252409/48527140-1a2a9600-e8c5-11e8-9d18-4173a8ac4d85.png)

**Comment by Justineo** [comment]
> 用户可以选择使用router或原生链接跳转，但也有不使用链接跳转的应用场景存在，所以翻页不一定都是链接，to可以作为不必要的补充属性

我改了一下标题，后续支持一下。

**Comment by sqliang** [comment]
> > 用户可以选择使用router或原生链接跳转，但也有不使用链接跳转的应用场景存在，所以翻页不一定都是链接，to可以作为不必要的补充属性
> 
> 我改了一下标题，后续支持一下。

**Comment by sqliang** [comment]
> > 用户可以选择使用router或原生链接跳转，但也有不使用链接跳转的应用场景存在，所以翻页不一定都是链接，to可以作为不必要的补充属性
> 
> 我改了一下标题，后续支持一下。

好的，我这边后续对齐下新的规范
