### ISSUE TITLE
未注册UI尚不支持直接使用，希望提供更友好api或者修复当前Bug

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui#378]
在自定义主题包，比如veui-theme-xxx中，通过使用config.defaults()或者config.set()方法可以定义预设样式。
比如：
![image](https://user-images.githubusercontent.com/29879262/48703734-a2939880-ec2f-11e8-8418-231fba5d414a.png)
在项目使用上面的主题包时，如果预设样式不满足要求，就需要增加自定义的样式，比如：
![image](https://user-images.githubusercontent.com/29879262/48703780-bccd7680-ec2f-11e8-823c-c2ff2fde318b.png)

然后这里的
![image](https://user-images.githubusercontent.com/29879262/48704032-7cbac380-ec30-11e8-903a-30edec137ce9.png)
ui="red"需要注册后才能使用

我们必须这样做才能让red主题生效
![image](https://user-images.githubusercontent.com/29879262/48703795-d242a080-ec2f-11e8-8752-3373f9d1f2a4.png)

或者
![image](https://user-images.githubusercontent.com/29879262/48703811-e1295300-ec2f-11e8-828b-fc72533de3bf.png)

不方便的地方：
1.需要先get(path)，再赋值回去，才能全部覆盖UI，不丢失；
2.需要知道主题包中每一项具体的UI设置；

希望：
1.提供更佳友好的api接口，例如：
![image](https://user-images.githubusercontent.com/29879262/48703972-53019c80-ec30-11e8-9975-2b4e866de2ad.png)

实现对Button的UI值的补充，而不是覆盖。
2.或者把当前问题当成Bug对待，修复
![image](https://user-images.githubusercontent.com/29879262/48703990-5eed5e80-ec30-11e8-91d9-ac0c4e8734b2.png)
这种写法不生效的问题。

**Comment by Justineo** [comment]
或者说未注册的就直接输出如何？
