### ISSUE TITLE
路径有问题

### ISSUE THREAD

**Issue by Lyd9607** [ecomfe/veui#380]
![default](https://user-images.githubusercontent.com/26515666/48765979-5ce9d500-ecee-11e8-97c7-23ecd18861fb.png)

**Comment by Justineo** [comment]
请给一下复现的步骤，谢谢。

**Comment by Lyd9607** [comment]
> 
> 
> 请给一下复现的步骤，谢谢。

就是克隆下来，执行bootstrap, 然后再执行dev的时候就会有这个

**Comment by fuchunhui** [comment]
刚才clone试了下，未发现有什么问题。所以请提供更详细内容复现步骤？
本机测试环境，Mac + node(8.12.0) + npm(6.4.1)

**Comment by 599316527** [comment]
> 刚才clone试了下，未发现有什么问题。所以请提供更详细内容复现步骤？
> 本机测试环境，Mac + node(8.12.0) + npm(6.4.1)

+1 我这里也正常。macOS 10.14.1 + node v10.7.0 + npm 6.4.1

你跑的是 `npm run bootstrap` 而不是 `npx lerna bootstrap` 吧

**Comment by Justineo** [comment]
目测用的 Windows，等我有空看一下吧。

**Comment by Justineo** [comment]
Closed via #381.
