### ISSUE TITLE
冗余代码？

### ISSUE THREAD

**Issue by bailnl** [ecomfe/veui#384]
非常感谢你们这个veui,  在我写组件库时提供了思路， 当然还有砖（代码）。

我在搬运代码的同时，感觉蓝色框框的代码是多余的。

![image](https://user-images.githubusercontent.com/2436993/49149089-25110c00-f344-11e8-849e-a7057d1b01cd.png)

代码位置： https://github.com/ecomfe/veui/blob/dev/packages/veui/src/managers/overlay.js#L572-L575

**Comment by Justineo** [comment]
https://github.com/ecomfe/veui/blob/4ccc98e23b0c6fe2dd252b3a3dfd0289b863af41/packages/veui/src/managers/overlay.js#L562

@yibuyisheng 你还记得这里只有第一次要 `normalizeIndex` 的目的是啥么？

**Comment by yibuyisheng** [comment]
@Justineo `findNextNode` 的 `groupIndex` 和 `childIndex` 参数都是可选的，某些情况下，外部是知道 `groupIndex` 或 `childIndex` 的，所以可以略微提升下查找速度。

**Comment by yibuyisheng** [comment]
@bailnl 篮框部分主要处理传入“合适”的 `groupIndex` 和 `childIndex` 的情况，红框乃至 `while` 块是针对未传入 `groupIndex` 和 `childIndex` 的分支情况。

那两段代码看起来比较相似，看起来似乎可以合起来。但是合起来之后，我感觉代码可能会很耦合，可读性不是太好。而且这俩段代码也不是很多，分开各自写一下也还能接受？

**Comment by Justineo** [comment]
先 close 了。

**Comment by bailnl** [comment]
@yibuyisheng 明白
