### ISSUE TITLE
Tabs 中动态添加标签时，有时受 offsetWidth 精度影响导致回调失败

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#397]
Reported by @xiaodemen.

`offsetWidth` return different values when the target element moves. Should use `getClientBoundingRect` instead.

**Comment by Justineo** [comment]
Fixed via #399.

**Comment by chestnutchen** [comment]
记得之前是说怕性能不好，讨论结果是牺牲一点精度。

**Comment by Justineo** [comment]
@chestnutchen 主要是之前没发现内容没变，仅仅平移也会让 `offsetWidth` 返回值不一样。
