### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#4]
## props

+ pageNo  第几页，默认：1
+ pageSize 每页多少条，默认：30
+ pageTotal 一共多少条
+ hrefTpl  链接模板，默认：`$page`
+ layout   布局类型，enum{basic, advanced, full, hetero}

## events

+ redirect 点击数字翻页时触发事件，回调函数接收目标页数

## usage

```html
<veui-pager :page-total="233" href-tpl="#!/path/to/page/$page/" />
```

```html
<veui-pager :page-total="233" @redirect="handlePageRedirect" />
```

**Comment by Justineo** [comment]
这个好像和 vue-router 也有关系？

**Comment by 599316527** [comment]
`href-tpl` 传入跟 vue-router 路由相同的 url pattern。点击链接时切换 hash，自动触发 vue-router 的切换。

另一个用法是，监听 redirect 事件阻止默认跳转，然后自行处理翻页行为，一般是页面内的局部翻页。

**Comment by Justineo** [comment]
感觉规范没描述清楚到底允许哪些 layout（比如有时候左右箭头在同一侧，有时候在两侧），目测不止 4 种，去发个 issue 问问 UE？

**Comment by 599316527** [comment]
UE 表示就这 4 种形态

**Comment by Justineo** [comment]
我看 Element 的实现方式是定义了每个部件的名字，然后可以自己编排顺序。不过似乎一般不太需要这么复杂。

**Comment by 599316527** [comment]
我想的就是每个部分都可以选择的话用起来就比较麻烦，所以这里的 layout 表示某个固定的组合形式。

**Comment by Justineo** [comment]
可以的，即使以后要扩展，`layout` 也可以作为套餐名字用。

**Comment by otakustay** [comment]
这个问题让我突然想起来那个grid system的可视化开发工具， @Justineo 知道那个东西，我们也有个属性类似那样子去声明各个部件的顺序似乎会蛮直观的
