### ISSUE TITLE
Select 组件升级

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#422]
初步想法：

- [ ] **Autocomplete** (@xiaodemen)

  新增，基于 Input。

- [ ] **TagInput** (@codeDebugTest)

  新增，部分功能基于 Autocomplete。

- [ ] **Select**

  - 增加 `filterable: boolean`

    基于 Autocomplete。

  - 增加 `multiple: boolean`

    基于 TagInput。

- [ ] **Searchbox**

  重构，基于 Autocomplete。

---

@ecomfe/veui

**Comment by feibinyang** [comment]
感觉新增一个组件比较好，比如 SearchSelect。 另外`filterable ` 这个是 `Function` 么

**Comment by Justineo** [comment]
@feibinyang `boolean`

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/56489558-af852280-6514-11e9-9a9b-b43318491845.png)
---
供参考。

**Comment by yibuyisheng** [comment]
要支持 Input 内超宽自动换行吗？

**Comment by Justineo** [comment]
@yibuyisheng 那肯定是要的吧。
