### ISSUE TITLE
AutoComplete 组件接口

### ISSUE THREAD

**Issue by xiaodemen** [ecomfe/veui#424]
## Props
datasource：Array.<String | {label, value}>
数据源。预定义的字段如下：
- label - 显示的值
- value - 实际数据

datasourceType: 'list' | 'tree'
数据源是 list 还是 tree

filter: (item, inputValue) => Boolean | {start, length}
匹配函数

value: String
组件的值，这个类型再讨论

suggestTrigger: String | Array.<String>
出现下拉的时机

placeholder，clearable，autofocus 和 input 一样

autoSuggestionOnClose: Boolean，默认false
当下拉关闭时还没选择建议的项，那么自动根据完全匹配的选择，没有匹配则清空

## Slots
input - 输入组件的 scoped slot

suggestions - 覆盖整个下拉组件的 scoped slot

suggestion - 覆盖每个下拉项的 scoped slot

## Events
`$emit('input', value)` : 同步输入组件中的值

`$emit('suggest', value)`：选中下拉时同步的值

**Comment by Justineo** [comment]
`datasourceType` 是不是不需要？`list` 就是一层的 `tree` 吧。

**Comment by xiaodemen** [comment]
可以这么理解，但是`tree`仅仅用第一层就成了`list`，可以默认不传，自动检测有没有`children: Array`?

**Comment by Justineo** [comment]
我觉得可以。

**Comment by feibinyang** [comment]
suggestTrigger  下拉时机是啥意思

**Comment by Justineo** [comment]
@feibinyang 见 [Searchbox](https://veui.dev/components/searchbox) 的 `suggest-trigger`。
