### ISSUE TITLE
DatePicker 日期选择 传入 type 不生效

### ISSUE THREAD

**Issue by weishuping** [ecomfe/veui#439]
为什么传入 type="month"不生效呢。
不是选择年-月的面板。依然是年-月-日的面板

**Comment by Justineo** [comment]
使用的版本 & 复现代码有么？

**Comment by weishuping** [comment]
veui": "^1.0.0-alpha.21",
代码：
         <veui-date-picker v-model="date" type="month"/>
你可以在你本地试下

**Comment by Justineo** [comment]
`type` 是 `1.0.0-alpha.24` 新增的。后续升级请关注一下 [release notes](https://github.com/ecomfe/veui/releases)。
