### ISSUE TITLE
TagInput 组件接口

### ISSUE THREAD

**Issue by codeDebugTest** [ecomfe/veui#483]
# props

prop   | type | default | desc
------------ | ------------- | ------------ | ------------
ui | string  |  |  全局UI 属性
datasource | Array | []  | 标签数据源，标签类型为 {label, value}
value | Array  |  | v-model，已输入 tags
input-trigger | string, array| enter | 插入一个 tag 的触发时机
suggest-trigger | string, array | input | 展示推荐列表的触发时机
readonly | boolean | false | 输入框是否为只读状态
disabled | boolean | false | 输入框是否为禁用状态
clearable | boolean | true | 是否显示清除按钮
composition | boolean | false | 是否感知输入法输入过程的值
autofocus | boolean | true | 是否显示清除按钮

# events
name | desc
---------| ----------
input | 有效输入时触发, 回调参数为 (value: array)。 v-model
change | 新增tag 或者 删除 tag 时触发，回调参数为 (value: string, event)。

# slots
name | desc
---------| ----------
suggestions |  推荐列表插槽。
suggestion | 推荐列表的选项插槽，用来定制单个选项。

**Comment by codeDebugTest** [comment]
补充： 实现复用 #429 中的 AutoCompleteBase.js

**Comment by Justineo** [comment]
我理解是不是内部直接是一个 `Autocomplete` 组件，然后定制 `before` slot 来显示已选项？这样 `Autocomplete` 支持的 props 都可以透传进去。
