### ISSUE TITLE
Tag 组件接口

### ISSUE THREAD

**Issue by codeDebugTest** [ecomfe/veui#486]
# props
prop | type | default | desc
--------| --------| --------|--------
ui | string |   | 预设样式： large  大尺寸； small 小尺寸
text | string |   | 内容
type | string |   | 标签样式： info  提示；success  成功；warning  警告；error  错误; 默认无样式
closeable | boolean | false | 是否允许关闭

# events
name | desc
------ | --------
close | 关闭标签时触发

# slots
name | desc
------ | --------
default | 内容区域。默认内容：内容文本。参数：text 内容文本

**Comment by Justineo** [comment]
1. 不需要 `text`，用默认 slot 就行了。
2. `closable`
3. 可能还需要允许用户自己制定颜色，待定
