### ISSUE TITLE
Loading 组件接口

### ISSUE THREAD

**Issue by fengChongxiu** [ecomfe/veui#498]
## props
| prop | type | default | desc |
|------| ---- | ------- | ----- |
| ui | string | small | spinner 的大小，枚举值为 small，large， middle |
| spinning | boolean | true | 是否处于加载状态 |
| spinner | string | - | 自定义加载图标的类名 |
| wrapperClass | string | - | 容器的类名 |
| background | string | - | 遮罩的背景颜色 |

## slots

| name | description |
| -----  | ----------- |
| default | loading 区域的内容|
| spinner | 自定义的 loading 动画 |
| tip | loading 的描述性文字 |

**Comment by Justineo** [comment]
这个组件可以等设计稿标好了再说。

但是 `wrapperClass`, `background` 这种 class 要来干嘛？

你开一个 `default` slot 包括了你所有的内容，那还要用这个组件干嘛……

**Comment by fengChongxiu** [comment]
行，我再好好琢磨下。
