### ISSUE TITLE
Uploader

### ISSUE THREAD

**Issue by r7r10t32** [ecomfe/veui#5]
## props
* uploaderType 上传类型，file或image
* name 数据名称
* action 提交地址
* files 已经上传了的文件
* throughIfame 是否通过iframe上传兼容ie9
* withCredentials 不通过iframe上传时，xhr的withCredentials
* headers 不通过iframe上传时，xhr的头部
* iframeCallbackType 通过iframe上传时，取值为‘postmessage’（通过postMessage回调）
    或者'func'（上传时把回调函数名传给后端，后端返回parent.veuiUploaderCallback【回调函数名】(data))
* convertResponse 一个用来转换后端返回数据的函数
    组件里用后端返回的data.status === 'success' 或data.status === 'failure‘来判断上传是否成功
    如果后端返回其他格式的data需要用这个函数进行转换
    函数的参数是后端返回的data，函数return的object需要包含status，值为'success'或'failure'
* disabled 是否禁用
* previewImage 上传类型是file时，是否显示小图预览
* extentionTypes 允许的扩展类型，字符串或数组
* maxSize 单个文件的大小限制，单位为MB
* maxCount 最多可以上传的文件数量，当超过这一数量时，会自动删除掉最先上传的文件
* needButton 上传类型是image时，上传按钮是列表外的button还是列表里的一个+号
* ui 样式 （multiline: 文件名过长时多行显示 ellipsis:文件名过长时截断 horizontal: 横向排列
     large: 上传类型是image时，显示大图 small: 显示小图
     bottom-mask: 上传类型是image时，预览图hover时使用在底部的局部遮罩浮层
     list-icon: 上传类型是file时，在文件列表的文件名前显示一个文件图标）
* uploadingContent 值为'text'显示uploadingText
    值为'progressPercent'显示进度百分比
    值为'progressBar‘显示进度条
    iframe模式时只能取'text'
* args 需要提交的额外参数，Object，value可以是常量或函数
* autoUpload 选完文件后是否自动上传
## slots
* tip: 提示内容
* warning: 警告内容
* button: 用来放置自定义的上传按钮，这个slot里只能放置一个节点，如果这个slot里有东西，会把本来的
    label的opacity设为0，并且宽高设置成和slot里的节点一样，但需要自己用css把slot里的button放到
    label下面
* file-content：文件列表每行的内容
* uploading-content：文件列表上传中的显示内容
* failure-content：文件列表上传失败的显示内容
## events
* change 添加新文件时的事件，参数为组件内部的fileList
* success 上传成功时的事件，参数为后端返回的data
* failure 上传成功时的事件，参数为后端返回的data
* delete 要删除文件时抛出的事件，参数为要删除的file
* cancel 要取消上传时抛出的事件，参数为要取消上传的file，在xhr模式下可以file.xhr.abort()

**Comment by Justineo** [comment]
## Props

| 名称 | 类型 | 默认值 | 含义 | 备注 |
| -- | -- | -- | -- | -- |
| name | String | -  | 表单项的名字 | `mixins/input` |
| value | Object | [] | 已上传的文件信息 | `mixins/input` |
| disabled | Boolean | false | 是否禁用 | `mixins/input` |
| readonly | Object | false | 是否只读 | `mixins/input` |
| action | String | - | 数据接口地址 | |
| accept | String | '' | 看看能否和[原生行为](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept)对齐 | |
| requestMode | 'xhr' / 'iframe' | 全局配置 `uploader.requestMode` | 上传模式 | |
| headers | Object<String> | 全局配置 `uploader.headers` | XHR 模式下的自定义请求头 | |
| withCredentials | Boolean| false | XHR 模式下是否带验证信息 | |
| convertResponse | Function | 全局配置 `uploader.convertResponse` | 后端接口返回数据的适配器 | |
| iframeMode | 'callback' / 'post-message' | 全局配置 `uploader.iframeMode` | 'iframe' 模式下回调的方式 | |
| payload | Object | {} | 额外的表单数据 | |

`xxxText` 还有上传按钮文字之类是否可以全部都走 slots / scoped slots 来做？现在的接口感觉有点太多了。有些样式上的到时候先找 UE 看最终视觉稿再说。

数据校验的话可以先找 @chestnutchen 对齐一下设计。

## Events

* complete - 上传结束
* success - 上传成功
* fail - 上传失败
* remove - 删除已上传的文件
* progress - XHR 方式下应该能拿到进度数据
