### ISSUE TITLE
Drawer 组件接口设计

### ISSUE THREAD

**Issue by xiaodemen** [ecomfe/veui#500]
## Props
| name | type | default | desc |
|------| ---- | ------- | ----- |
|open| boolean?|-|打开|
|placement| enum | 'right'|滑动方向:'top' / 'right' / 'bottom' / 'left'|
|maskClosable| boolean| true| 点击遮罩时关闭|
|closable|boolean|true|是否有关闭按钮|
|escapable|boolean|true|按`Esc`关闭|
|priority|number|-|z-index|
|title|string|-|title文案，和 `Dialog` 一样|

## Slots
和 `Dialog` 一样,即 title，default，foot

## Events
|name|args|when|
|------| ---- | ----|
|ok|-|点击确认|
|cancel|-|点击mask或关闭按钮|
|update:open|true/false|

过渡的 duration 等要暴露成 prop 吗，要定制这些直接让使用者写 css 吧？
现在 `Overlay` 的 0.2s opacity  transition 有点影响滑出，做成两个串行的 transition ?

**Comment by Justineo** [comment]
> maskClosable

这个是不是做成 `closable: true` 时的默认行为？

> 过渡的 duration 等要暴露成 prop 吗，要定制这些直接让使用者写 css 吧？

不用吧，这个不让在调用组件时定制。

> 现在 `Overlay` 的 0.2s opacity transition 有点影响滑出，做成两个串行的 transition ?

这个可以用 CSS 覆盖掉的吧。

**Comment by Justineo** [comment]
整体逻辑感觉和 `Dialog` 几乎是完全一样的，差异点不多：

- 没有拖拽
- 支持四周定位

有没有可能直接包一个 `Dialog` 实现？
