### ISSUE TITLE
DLS-18 一期进度

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#512]
开发时注意下面几点：

1. 尽量使用 flex 布局处理对齐等场景，`veui-theme-dls` 的兼容性已调整为兼容到 IE11。
2. 所有的样式值（颜色、尺寸、阴影等）不允许使用硬编码，必须来自 `less-plugin-dls` 指定的组件样式变量。理论上每个变量都应该被用到，才能说明组件实现了设计稿的设计规范。另外建议安装对应的 [VSCode 扩展](https://marketplace.visualstudio.com/items?itemName=justice360.vscode-dls)，来获得变量的自动补全。

    > 变量名命名约定
    >
    > `@dls-{component}-{part?}-{property}-{variant?}-{status?}-{action?}`
    >
    > 例如对于：`@dls-input-border-color-read-only-hover`，解释为 `input` 组件 `read-only` 状态下，`hover` 时的 `border-color`。

    设计标注上标的一般是 B6/3P/S1 这样的全局单位，请直接引用组件文件里的变量而非全局变量。

3. 如果有必要修改组件的模板和JS代码，请先和大家讨论一下。
4. `ui` 属性值中，`size` 要支持哪些请看对应组件的[变量文件](https://github.com/ecomfe/less-plugin-dls/blob/master/tokens/components/)。
5. VEUI 现在的机制支持指定某一个组件的某个具体子组件采用什么 `ui` 值，可以参考[这里](https://github.com/ecomfe/veui/blob/8ef68f9fd7c732a4c1fcae9637c44b7a8b6f6501/packages/veui-theme-dls/components/Dialog.js#L15-L17)以及[这里](https://github.com/ecomfe/veui/blob/8ef68f9fd7c732a4c1fcae9637c44b7a8b6f6501/packages/veui/src/components/Dialog.vue#L62-L65)。
6. 当需要为不同的 `ui` 指定不同的图标时，可以参考[这里](https://github.com/ecomfe/veui/blob/8ef68f9fd7c732a4c1fcae9637c44b7a8b6f6501/packages/veui-theme-dls/components/NumberInput.js#L14-L31)。
7. 不针对 `:focus` 编写样式，而针对 `.focus-visible` 编写对应样式。原因见[这里](https://veui.dev/getting-started/focus-visible)。
8. 开发前请重新安装依赖，并在整个 repo 根目录下运行 `npm run bootstrap`。

---

### 开发进度

🎨= Style Update, 🔧= New Feature, 📦= New Component

✅= Done, 🔬= Reviewing, 🚧= Developing

| 组件 | 升级内容 | 负责人 | 变量 | 开发 | 备注 |
| -- | :--: | -- | :--: | :--: | -- |
| Button | 🎨 | @zhangjialiang | ✅ | ✅ | |
| Link | 🎨 | @zhangjialiang | ✅ | ✅ | |
| Pagination | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Breadcrumbs | 🎨 | @Justineo | ✅ | ✅ | |
| Anchor | 📦 | @xiaodemen | ✅ | ✅ | |
| Steps | 🎨 🔧 | @StarShinny | ✅ | ✅ | |
| Tree | 🎨 | @r7r10t32 | ✅ | ✅ | |
| Transfer | 🎨 | @r7r10t32 | ✅ | ✅ |  |
| Tabs | 🎨 | @HankLiang | ✅ | ✅ | |
| Menu | 📦 |@xiaodemen | ✅ | 🚧 | |
| Slider | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| TimePicker | 📦 |@xiaodemen | ✅ | ✅ | |
| Switch | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Radio | 🎨 | @Justineo | ✅ | ✅ | |
| Checkbox | 🎨 | @Justineo | ✅ | ✅ | |
| RadioGroup | 🎨 | @Justineo | ✅ | ✅ | |
| CheckboxGroup | 🎨 | @Justineo | ✅ | ✅ | |
| ButtonGroup | 🎨 | @Justineo | ✅ | ✅ | |
| RadioButtonGroup | 🎨 | @Justineo | ✅ | ✅ | |
| CheckboxButtonGroup | 🎨 | @Justineo | ✅ | ✅ | |
| Tag | 📦 | @codeDebugTest | ✅ | ✅ | |
| Select | 🎨 🔧 | @codeDebugTest | ✅ | ✅ | |
| Dropdown | 🎨 🔧 | @fengChongxiu | ✅ | ✅ | |
| SearchBox | 🎨 🔧 | @fengChongxiu | ✅ | ✅ | |
| Input | 🎨 🔧 | @Justineo | ✅ | ✅ |  |
| NumberInput | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Textarea | 🎨 🔧 | @Justineo | ✅ | ✅ |  |
| Carousel | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Collapse | 📦 | @Justineo | ✅ | ✅ | |
| Dialog | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Embedded | 📦 | @Justineo | ✅ | ✅ | |
| Drawer | 📦 | @xiaodemen | ✅ | ✅ | | 多级交互需要再确认 |
| Tooltip | 🎨 | @HankLiang | ✅ | ✅ | |
| Popover | 📦 | @HankLiang | ✅ | ✅ | |
| Progress | 🎨 🔧 | @Justineo | ✅ | ✅ | |
| Loading | 📦 | @fengChongxiu | ✅ | ✅ | |
| Badge | 📦 | @Justineo | ✅ | ✅ | |
| Toast | 🎨 🔧 | @HankLiang | ✅ | ✅ | |
| Alert | 🎨 | @HankLiang | ✅ | ✅ | |

**Comment by codeDebugTest** [comment]
-  Pagination
- Breadcrumbs
- Anchor
- Badge

**Comment by StarShinny** [comment]
- Steps

**Comment by fengChongxiu** [comment]
- Dropdown
- Searchbox

**Comment by HankLiang** [comment]
- tab
- Tooltip
- Alert

**Comment by HankLiang** [comment]
> * tabs
> * Tooltip
> * Alert

**Comment by HankLiang** [comment]
- Tabs
- Tooltip
- Alert

**Comment by xiaodemen** [comment]
Menu 好像就是 Tabs，那就给 @HankLiang 吧

**Comment by Justineo** [comment]
@xiaodemen 并不是，横向的是 Tabs，纵向的不是
