### ISSUE TITLE
veui-input  输入时 placeholder 不隐藏

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#535]
1. veui-input  输入时 placeholder 不隐藏

```vue
<template>
    <veui-input :value="price" placeholder="占位符占位符" @change="handlePriceChange" />
</template>

<script>
export default {
    methods: {
        handlePriceChange(val) {
            this.price = val;
        }
    }
}
</script>
```

![Screen Recording 2019-08-16 at 19 50 28](https://user-images.githubusercontent.com/1331413/63165992-a68a0500-c05f-11e9-9f35-73be11339186.gif)

2. veui-number-input 输入无效

```
<veui-number-input :value="price" @change="handlePriceChange" />
```

![Screen Recording 2019-08-16 at 19 51 17](https://user-images.githubusercontent.com/1331413/63166049-ca4d4b00-c05f-11e9-846a-49d29a04b44c.gif)

**Comment by Justineo** [comment]
Fixed in #536.
