### ISSUE TITLE
ButtonGroup 事件回调参数增加 event 对象

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#540]
某些情况下需要感知按钮点击时的 MouseEvent 上面的信息

**Comment by Justineo** [comment]
比如啥信息？

**Comment by 599316527** [comment]
`MouseEvent.altKey` `MouseEvent.ctrlKey` `MouseEvent.metaKey` `MouseEvent.shiftKey`
`MouseEvent.button`
`MouseEvent.webkitForce`
...

**Comment by Justineo** [comment]
了解了，是想加快捷键

**Comment by Justineo** [comment]
Implemented in 343334e5aba9ab860dff8ff77f38e79ce096cb86.
