### ISSUE TITLE
v-drag: dragStart 里面能不能通过返回值决定是否取消这次拖动

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#551]
在有个拖动元素上增加右键菜单，发现右键也可以拖动，增加一个限制鼠标左、右键拖动的选项，或者允许使用者在 dragStart 里面自行觉得是否开始拖动。

```
function dragStart({event}) {
    if (event.button !== 0) throw new Error('打断拖动');
}
```

**Comment by 599316527** [comment]
drag options 支持传入指定 left|right|both 哪个鼠标按键触发拖动

**Comment by 599316527** [comment]
同一个 element 同时支持点击和拖动行为。
希望 drag options 支持传入 delay 参数，mousedown 等待 delay 毫秒后再开始 dragStart。如果在 delay 期间 mouseup 了就不执行拖动

**Comment by 599316527** [comment]
希望增加 dragCancel 回调。
拖动过程中，如果拖到窗口外面、出右键菜单等情况算在拖动取消。
程序可以判断 cancel 来 revert change

**Comment by Justineo** [comment]
> drag options 支持传入指定 left|right|both 哪个鼠标按键触发拖动

发现右键按下拖动到窗口外释放不会触发 `mouseup` 事件，所以实际上似乎没有办法支持右键拖动。如果的确如此的话可以考虑直接只在 `event.button === 0` 时触发整个流程。

> 同一个 element 同时支持点击和拖动行为。
> 希望 drag options 支持传入 delay 参数，mousedown 等待 delay 毫秒后再开始 dragStart。如果在 delay 期间 mouseup 了就不执行拖动

我感觉还是在 `drag` 回调里面处理一下下次点击。delay 的话其实还要区分等待时间到了先触发 drag 还是先触发 click 吧？

> 拖动过程中，如果拖到窗口外面、出右键菜单等情况算在拖动取消。
> 程序可以判断 cancel 来 revert change

在 dragend 里面返回是否出了窗口行么？出右键菜单应该就没法拖动了……

**Comment by Justineo** [comment]
下个版本准备在 `dragend` 中提供一个 `cancel` 方法，可以回退到上一次触发 dragstart 的位置，调用如下：

```html
<div ref="self" v-drag:self="{
  dragend: dragEnd
}">foo</div>
```

```js
dragEnd ({ distanceX, cancel }) {
  if (distanceX > 100) {
    cancel()
  }
}
```

**Comment by Justineo** [comment]
Implemented in #560.
