### ISSUE TITLE
Menu API 设计

### ISSUE THREAD

**Issue by xiaodemen** [ecomfe/veui#555]
## Props
| name | type | default | desc |
|------| ---- | ------- | ----- |
| link | Boolean | true | menu item 采用 link 还是 span |
| items | [{ value, label, children, icon }] | [] | menu数组 |
| expanded | Array | [] | 参见Tree |
| collapsed | Boolean | false | 当items有icon时用来控制进入折叠状态 |
| active | any | -- | 非link模式下，控制当前激活的item |
| match | route => ({active: Boolean, exactActive: Boolean}) |  | link模式下用来定制匹配item的逻辑 |
| autoExpandActive | Boolean | true | 默认自动会打开激活的item（名字可以讨论下）|

## Events
| name | args | desc |
|------| ---- | ---- |
| click | item | 非link模式下点击 item 会触发 |

**Comment by Justineo** [comment]
- 不需要 `link` 来判断用 link 还是 span，直接用 `<veui-link>` 会根据有没有 `to` 来判断吧
- `expanded` 需要有 unique `name`，这里似乎没有吧，`active` 同理
- 需要有一个 `collapsible`
- `match` 是不是和 Tabs 的 `matches` 保持一致？
- `autoExpandActive` 这个感觉可以先不加，再想想
