### ISSUE TITLE
Uploader 样式优化 

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#557]
https://github.com/ecomfe/veui/blob/ad5488ef5324fd29d6e3ca841fb3040e50b19a1a/packages/veui-theme-one/components/uploader.less#L74-L91

`.veui-uploader-list-image img` 的绝对定位应该约束到 `.veui-uploader-list-image-container img` ，否则会影响到 file-before|after 里面的 img

**Comment by Justineo** [comment]
Fixed.
