### ISSUE TITLE
支持在运行时注入 manager

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#567]
为了支持一个页面中存在多个版本 VEUI/多个主题的 VEUI 时（引入的 SDK 自带了已编译的 VEUI 组件），需要提供一个运行时的注入机制，让多个 VEUI 可以共享同一个全局 manager，比如共享 overlay manager 使来自不同源的浮层可以统一管理。

可能的 API：

```js
import config from 'veui/managers/config'

export function setOverlayManager(instance) {
  config.set('managers.overlay', instance)
}
```

外部使用时如果引用的不是同一个 VEUI 模块，就可以如此调用：

```js
import { setOverlayManager } from 'sdk'
import overlay from 'veui/managers/overlay'

setOverlayManager(overlay)
```

需要注意的是，需要支持注入的 manager 在 VEUI 进行调用时，也需要优先获取全局 config 中的配置。

**Comment by 599316527** [comment]
多个版本的 veui 的 manager 如果出现 breaking change 就没法用了。感觉得在 setOverlayManager 实现一个 validate 方法来前置校验 manager ，而不是运行时跑出错了才发现。

**Comment by Justineo** [comment]
Breaking change 在 runtime 可能比较不好实现，最多是判断一下指定的那几个方法存不存在，但是无法保证行为是一样的。不过这个 feature 如果要实现，则必须把 overlay manager 的接口变成 public API，理论上不应该有 breaking change 了（这个可能比较难做到）。

**Comment by 599316527** [comment]
加个 version 判断 🙃

**Comment by Justineo** [comment]
Implemented via 2c998744f46385ad295c1cf2280503cd09e3bd5a.
