### ISSUE TITLE
OptionGroup 不渲染 label slot

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#575]
https://github.com/ecomfe/veui/blob/ff1a5095130301d9bdd93dae6c3e67f330647332/packages/veui/src/components/Select/OptionGroup.vue#L226-L263

看了代码，只有在传入 label props 时才能进 label slot 的分支，否则不渲染。

label slot 和 label 应该是 二选一 的才对呀。

**Comment by Justineo** [comment]
看起来是一个 bug。
