### ISSUE TITLE
Tabs tabs-item click setActive传值错误

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#579]
https://github.com/ecomfe/veui/blob/f8ec954f2cf1f9d5f542466b8b3b644d6bc915fc/packages/veui/src/components/Tabs/Tabs.vue#L53

`{ i }` -> `{ index: i }`
  
https://github.com/ecomfe/veui/blob/f8ec954f2cf1f9d5f542466b8b3b644d6bc915fc/packages/veui/src/components/Tabs/Tabs.vue#L444

**Comment by Justineo** [comment]
直接给 `dev` 分支发 PR 吧

**Comment by 599316527** [comment]
另外一个问题，这个bug触发后再点击 button 就失效了

![Screen Recording 2019-11-05 at 12 32 06](https://user-images.githubusercontent.com/1331413/68178936-be22bb00-ffc8-11e9-90ea-de80ac9f61b9.gif)

**Comment by 599316527** [comment]
https://github.com/ecomfe/veui/blob/f8ec954f2cf1f9d5f542466b8b3b644d6bc915fc/packages/veui/src/components/Tabs/Tabs.vue#L444-L447

应该是这里。没有设置 tab.name ，activeIndex < 0 之后 `active === undefined`，`this.localActive === active` 永远为 true，就没法再 active 任何一个 tab 了。

**Comment by Justineo** [comment]
Fixed in #580.
