### ISSUE TITLE
在文档中未找到“菜单”的使用方式

### ISSUE THREAD

**Issue by zlzforever** [ecomfe/veui#601]
菜单的各种样式是否有呢？

**Comment by Justineo** [comment]
你说的是哪个菜单？

**Comment by zlzforever** [comment]
https://cloud.tencent.com/developer/section/1489896  导航菜单

**Comment by Justineo** [comment]
现在导航菜单还在开发中，目前会是和 Tabs 相同的设计。如果只有单层导航，可以先用 Tabs 代替。
