### ISSUE TITLE
Dialog modal启用时也要禁止滚动页面

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#607]

**Comment by Justineo** [comment]
两个方案：

1. 打开 `modal` 的浮层时，将 `document.body` 的 `overflow` 设置为 `hidden`。但是这样会导致有/无滚动条时页面内容发生抖动，有几率影响整体布局（比如本来不折行的折行了）。
2. 监听遮罩层本身的 `mousewheel` 事件，并且 `preventDefault` 处理，可以屏蔽但无法处理用户直接点击/拖动滚动条。

需要再考虑一下有没有更好的方案，或者采取其中一种做临时处理。

**Comment by Justineo** [comment]
body scroll lock 将在下个版本中发布。

**Comment by Justineo** [comment]
Shipped in `2.0.0-alpha.6`.
