### ISSUE TITLE
Uploader 文件扩展名校验逻辑存在缺陷

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#646]
https://github.com/ecomfe/veui/blob/43fdc47750bfa2163b732a4898dad0ae22ea011b/packages/veui/src/components/Uploader.vue#L829

当传入 `tar.gz` 而不是 `.gz` 作为合法扩展名时，选择 `*.tar.gz` 文件会报错。

**Comment by r7r10t32** [comment]
浏览器不支持中间带点的扩展名，可以用mime类型，例如.tar.gz -> application/x-gzip

**Comment by Justineo** [comment]
@r7r10t32 在文档里加个 warning block 说明一下？

**Comment by 599316527** [comment]
试了下 Windows 上可以。有人报过 bug，Chromium 甩锅给了 OS https://bugs.chromium.org/p/chromium/issues/detail?id=521781
