### ISSUE TITLE
Popover 不支持 ui 属性

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/veui#656]
**现象**：虽然在调用时传 `ui="m"` 的 `prop`，但是并没有生效，最终渲染的 `overlay`不包含这个 `prop`，情况如图：
![image](https://user-images.githubusercontent.com/2435478/80573733-1ea02b80-8a33-11ea-8243-18438377336f.png)

**原因**：虽然 DLS 样式中支持 `s/m` 两种 ui([代码详情](https://github.com/ecomfe/veui/blob/theme-dls/packages/veui-theme-dls/components/popover.less#L20-L30))，但是组件里面并没有把 'ui' 传递给 `overlay`，并且 `Tooltip` 也不支持透传这个 `prop`，代码详情如下：

- Popover: 只传递`reverse` 给 `tooltip`，没有把`this.$props.ui`或者`this.ui`传递给下去。 [详情](https://github.com/ecomfe/veui/blob/theme-dls/packages/veui/src/components/Popover.vue#L20)

- Tooltip: 不支持透传 `ui` 给 `Overlay`。[详情](https://github.com/ecomfe/veui/blob/theme-dls/packages/veui/src/components/Tooltip.vue#L178) 

**定位**：不确定这是设计如此（CSS 多余的？），还是这个 bug。

**修复方案**：如果是 bug 的话，感觉 `Tooltip`可以增加一个 `overlayUi`的`prop`， 渲染 `Overlay` 的时候把它传下去，`Popover`在渲染的时候把当前 `this.ui`传递给`Tooltip`。如果确定方案可行的话，我这边提个 pr

**Comment by Justineo** [comment]
现在的逻辑其实是这样的：

`veui-theme-dls` 里定义了 `Popover` 接受 `m`/`s` 两个 `ui` 值，又定义了内部 `Tooltip` 的预设 `ui`（`uiParts.self`）是 `reverse`，但是只传了 `uiParts.self` 给 `Tooltip`，自己的 `realUi` 丢了。这里应该只需要在给 `Tooltip` 传参数的时候把两块合并起来就行了。

然后 `popover.less` 里定义的样式是写在 `[ui~="s"] .veui-tooltip` 上的，这个改成 `.veui-tooltip[ui~="s"]` 比较合适，不需要加 `overlayUi` 把这些逻辑暴露出来。

**Comment by feibinyang** [comment]
好的，那我修改下。我以为和 `dropdown` 一样在 `overlay` 上加 `ui` 呢
![image](https://user-images.githubusercontent.com/2435478/80673055-db03fb00-8ae0-11ea-945a-427322f27864.png)

**Comment by Justineo** [comment]
Fixed in #657.
