### ISSUE TITLE
Form/Fieldset/Field D20 样式更新

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/veui#662]
这是我梳理的改动点，帮忙 review 下。

##### `form.less` 需要更新的变量

- @dls-form-label-spacing-after-horizontal: @dls-padding-unit * 3; // 12px

- @dls-form-label-spacing-after-inline-horizontal: @dls-padding-unit * 8; // 32px

- @dls-form-label-font-color: @dls-foreground-color-neutral-active; // #000

  

##### form.js

```
import config from 'veui/managers/config'

config.defaults(
  {
    ui: {
      display: {
        values: ['inline', 'right', 'left', 'top'],
        default: 'right'
      },
    },
    parts: {
      ok: 'primary'
    }
  },
  'form'
)
```

##### fieldset.js(不变么？alt style 样式设计？)

```
import config from 'veui/managers/config'

config.defaults(
  {
    ui: {
      style: {
        values: ['alt']
      }
    }
  },
  'fieldset'
)
```

##### field.js

```
import 'veui-theme-dls-icons/question-circle'
import config from 'veui/managers/config'

config.defaults(
  {
    icons: {
      tip: 'question-circle'
    },
    ui: {
      size: {
        values: ['l', 'm', 's', 'xs'], // large/small/micro/tiny
        inherit: true
      }
    }
  },
  'field'
)
```

##### Form

- `prop` 不变，`ui` 扩展了 `right/left/top`三个值，分别表示对齐方式，默认为 `right`

##### Fieldset

*⚠️没有 error 设计稿，另外 alt 样式也没有设计稿？* 

###### prop 不变

`tip`表示提示信息内容，默认为`''`。如果不为`''`就在 label 内容后显示 icon，鼠标悬浮显示信息内容

###### slot

删掉 `tip` 这个 slot。

###### prop

保持不变，其中 `ui`属性值为`l/m/x/xs`分别替换原先`large/small/micro/tiny`

###### slot

删掉 `tip` 这个 slot。

error 信息删掉 icon。

**Comment by Justineo** [comment]
> `form.less` 需要更新的变量

没看懂这个，啥意思？

> ##### form.js

`display` 这个先不要加，先实现最常见的那种右对齐吧。

> ##### fieldset.js(不变么？alt style 样式设计？)

删掉 `alt`。


> 没有 error 设计稿

![image](https://user-images.githubusercontent.com/1726061/81276518-b500cc80-9085-11ea-9482-70a352e60842.png)

这里面有吧

> 删掉 `tip` 这个 slot。

这个不用删掉吧，可以显示在 Tooltip 里边。

**Comment by Justineo** [comment]
Implemented in #666.
