### ISSUE TITLE
Alert 不同 message 个数情况下 extra slot 行为不一致

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#685]
message 传入 string 时，extra slot 不能是 scoped slot，但传入 array 时可以是 scoped slot。

https://github.com/ecomfe/veui/blob/dff92b31d81a1d6d5efdc3358258b8d3230ed228/packages/veui/src/components/Alert.vue#L32

https://github.com/ecomfe/veui/blob/dff92b31d81a1d6d5efdc3358258b8d3230ed228/packages/veui/src/components/Alert.vue#L66

要实现“如果只有单个 message 就不显示切换按钮（< 1/1 >），多个 message 时才显示切换按钮”的需求，可以通过传入不同类型的 message类型来实现。但由于上述 extra slot 的差异，导致无法通过这一方式实现。由于两种情况下 extra slot 的行为差异，只能通过 v-if 切换两种情况来实现。

```
:message="messages.length > 1 ? messages : messages[0]"
```

**Comment by Justineo** [comment]
Closed via #694.
