### ISSUE TITLE
dev 阶段移除部分 eslint 规则

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#7]
像变量没有使用、缩进错误、数组逗号等并不影响代码运行的规则能否不要在 dev 时检查，否则 debug 时比较麻烦。

这些检查可以配置到 git commit 的 hook 上进行检查。

**Comment by Justineo** [comment]
这个可以本地改 `.eslintrc` 然后不提交嘛。

**Comment by 599316527** [comment]
我现在是这么搞的，但一不小心就提交了 https://github.com/ecomfe/veui/pull/6/commits/2a3611c3c3f7390d1454c64d3230780360d0090e#diff-e4403a877d80de653400d88d85e4801aR27

而且，这样的话，提交的代码就可能跟规范不符。

**Comment by otakustay** [comment]
webpack在dev环境下不使用eslint不就好了，然后在travis上加eslint，反正不通过不能merge

**Comment by 599316527** [comment]
可以。但最好  git hook 也加上，否则会出现各种 fix code style 的 commit

**Comment by otakustay** [comment]
能加上最好，当然pull request用squash merge也是个办法
