### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by gnsilence** [ecomfe/veui#704]
集成到项目中按照配置要求完成配置,依然没办法运行起来,错误如下:
* ../../utils/data in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/veui-loader/lib??ref--13-0!./node_modules/veui/components/Select/OptionGroup.vue?vue&type=script&lang=js&

另外有没有可以运行的demo项目

**Comment by Justineo** [comment]
https://github.com/ecomfe/veui/blob/d20/packages/veui/README.md

是按这里的说明配置的吗？

**Comment by gnsilence** [comment]
> https://github.com/ecomfe/veui/blob/d20/packages/veui/README.md
> 
> 是按这里的说明配置的吗？

是的,试了几次都有问题,最后放弃用这个了
