### ISSUE TITLE
veui-field不支持包含自己的表单组件实时验证( 比如原生input，换成veui-input就ok) 

### ISSUE THREAD

**Issue by baoleilei** [ecomfe/veui#721]
```
<veui-field
         name="register_years"
         field="register_years"
         label="执业年限"
          :rules=" {
                  name: 'required',
                  value: true,
                   triggers: 'blur,input'
        }"
 > 
       <input placeholder="请输入您的从业年限" v-model="formData.register_years"/>
</veui-field>
```

这样不ok

```
<veui-field
      name="register_years"
      field="register_years"
      label="执业年限"
      :rules=" {
           name: 'required',
           value: true,
           triggers: 'blur,input'
        }"
> 
     <veui-input placeholder="请输入您的从业年限" v-model="formData.register_years"/>
</veui-field>
```

这样就ok

**Comment by Phinome** [comment]
什么场景下需要使用原生的 `input` 呢？

**Comment by Justineo** [comment]
@Phinome 不一定是原生的 `<input>`，也可以是某个 VEUI 不支持的第三方组件，比如 `ColorPicker`。

**Comment by Phinome** [comment]
这如果要支持就需要向下遍历第三方组件的节点了吧，或者给个 hook？

**Comment by Justineo** [comment]
VEUI 的对输入组件的通用处理（通过 `mixins/input`）：

1. 会”继承“上层 `Field`/`Fieldset`/`Form` 的 `readonly`/`disabled` 状态。
2. 把所有自身触发的事件代理到 `Field` 上（重写了 `$emit` 把所有除了 `update:*` 和 `hook:*` 的事件都在 `Field` 上触发了一遍），这样 `Form` 可以根据配置的校验触发时机（`triggers`），在特定的输入组件的指定时机进行校验。

---

是的，如果不能依赖自下而上的逻辑（不确定传入的输入组件来自哪里），就只能自上而下去遍历了。

**Comment by baoleilei** [comment]
请问下这个什么时候可以支持？ 比较急了....

**Comment by Phinome** [comment]
我研究了一下，有了两个想法，希望在这里讨论一下：
1. 遍历 `veui-field` 的 `default slots` 数组的每一个 VNode 的 `child`。寻找 `input` 的 `value` 与 `v-model` 匹配项，将 `Field` 或者 `Form` 的校验规则以及状态，作用于它；
2. 遍历 `veui-field` 的 `default slots` 数组的每一个 VNode 的 `data` 对象。通过从 `directives` 数组或者 `model` 对象中找到 `v-model` 绑定的对象，将校验规则作用于这个 `v-model` 的对象，将状态传入这个 `data` 的 `props` 并触发强制更新。从而达到目的。
除上诉两个思考外，暂时没有更好的解决问题的路径，请教 @Justineo 可否指点一二，2333

**Comment by Justineo** [comment]
已经支持，参见[文档示例](https://veui.dev/components/form#%E5%8E%9F%E7%94%9F%E8%BE%93%E5%85%A5%E6%A1%86%E4%B8%8E%E8%A1%A8%E5%8D%95%E9%A1%B9%E6%95%B4%E5%90%88)。
