### ISSUE TITLE
转义CSS中的零宽空格字符？

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#724]
## 现状

现在 CSS 中零宽空格有两种写法：

https://github.com/ecomfe/veui/blob/708fa52476aa9c1bff2f2b0ad73dcfe9b429110f/packages/veui-theme-dls/components/button.less#L17-L19

https://github.com/ecomfe/veui/blob/708fa52476aa9c1bff2f2b0ad73dcfe9b429110f/packages/veui-theme-dls/components/progress.less#L17-L19

![Mozilla_Firefox-2](https://user-images.githubusercontent.com/1331413/96545344-c871be00-12da-11eb-9fad-aa4b8a6c4e33.jpg)

## 问题 

对于后一种，目前碰到一个诡异的情况：浏览器可能错误地识别了 css 文件的编码，从而将零宽空格显示为了其它字符（乱码），但未找到稳定复现的方法。

![Screen_Shot_2020-10-20_at_13_07_19](https://user-images.githubusercontent.com/1331413/96545488-0f5fb380-12db-11eb-90ca-5381f7bc77af.jpg)

![Pasted_Image_2020_10_20__13_57](https://user-images.githubusercontent.com/1331413/96546161-55694700-12dc-11eb-92ec-44de03e92cf5.jpg)

## 期望解决方案

虽然可能可以(未验证)为静态资源服务设置 `content-type` 同时输出 `charset` 的配置，但这对于前端框架来说不太友好。

希望可以按照前一种写法书写零宽空格 或者在编译时处理转义 来避免这一问题。

**Comment by Justineo** [comment]
统一改成 `\200b` 吧。
