### ISSUE TITLE
Tabs组件文档问题

### ISSUE THREAD

**Issue by neo-to** [ecomfe/veui#727]
[https://veui.dev/components/tabs](url) 这部分关于`slot`的文档描述好像是错误的
修改tab的label的插槽名字应该是`tab-label`而不是`tab-item-label`

**Comment by Justineo** [comment]
谢谢指出。

**Comment by neo-to** [comment]
> 谢谢指出，实际应该是 `tab-item-label` 的，是组件实现错误。参见：#635
> 
> > * 新增了 `tab-item-label` scoped slot 用来仅自定义标签内容

感谢

**Comment by Justineo** [comment]
考虑了一下，为了不引起 breaking change，决定还是把该 slot 重命名为 `tab-label`。更简单一些，应该也没有歧义。

**Comment by neo-to** [comment]
> 考虑了一下，为了不引起 breaking change，决定还是把该 slot 重命名为 `tab-label`。更简单一些，应该也没有歧义。

建议只保留一个  看了一下源码目前应该是两个都生效吧

**Comment by Justineo** [comment]
不是的，只有 `tab-label`。

**Comment by neo-to** [comment]
> 不是的，只有 `tab-label`。

看错了 把类名看成插槽名了😹
我这还有一个疑问 我看`Tab`组件源码发现支持的插槽应该是三个 `item` 和`label` 以及默认的`default`
但是文档上的描述是不是也不太对啊  `item`给描述成了`item-label`

**Comment by Justineo** [comment]
Tabs/Tab 之前重写了一版，可能是文档对应的地方没有及时更新。我们一起修一下。
