### ISSUE TITLE
uploader remove事件回调可能缺少参数

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#747]
![image](https://user-images.githubusercontent.com/1331413/99500894-f15aa100-29b5-11eb-84e9-6c48734f1141.png)

```
<veui-uploader @remove="handleUploaderFileRemove" ...
-------
        handleUploaderFileRemove({status}) {
            ga('send', 'event', 'uploader', 'click', 'remove_button', status);
        },
```

上述代码，监控到发生报错：

![image](https://user-images.githubusercontent.com/1331413/99501198-67f79e80-29b6-11eb-9be6-1e92f013c070.png)
![image](https://user-images.githubusercontent.com/1331413/99501279-8493d680-29b6-11eb-98bd-4aaa139e0890.png)

**Comment by Justineo** [comment]
Should already been fixed.
