### ISSUE TITLE
Table 支持表头 Tooltip 功能设计

### ISSUE THREAD

**Issue by Phinome** [ecomfe/veui#748]
### Prior art

<details>
开放的主要 prop：

#### Ant Design

没有提供用于配置表头 `tooltip` 的 `props`

##### Table
| prop | 描述 | 类型 |
| -- | -- | -- |
| tooltip-effect | tooltip effect 属性 | Enum(dark, light) |

##### TableColumn

| prop | 描述 | 类型 |
| -- | -- | -- |
| show-overflow-tooltip | 当内容过长被隐藏时显示 tooltip | Boolean |

#### Fusion Next

没有提供用于配置表头 `tooltip` 的 `props`

#### 只有 ElementUI 支持在内容过长被隐藏时显示 `tooltip`，Antd 和 Fusion 皆不支持。猜测是因为表头支持自定义 `Render`，因此，交给业务开发者自行处理。

| 功能 | Ant Design | Element | Fusion Next |
| -- | -- | -- | -- |
| 配置 tooltip effect 属性 | - | tooltip-effect | - |
| 当内容过长被隐藏时显示 tooltip | - | show-overflow-tooltip | - |

</details>

---

##### Column prop

* `desc: Optional<String> ` - 对表头内容做进一步补充的说明的文本

---

### 最小化实现

* Column prop 新增 `desc` 属性

**Comment by Justineo** [comment]
我感觉可以给 Column 新增一个 `desc` prop，有的话就直接通过 Popover（非 Tooltip）展现。

另外这个功能不是给超长截断用的，而是在需要对表头做额外解释的时候。比如说，有一列“点击率”，浮层展现的应该是点击率是如何计算出来的说明。

**Comment by Phinome** [comment]
原来如此，`desc` 合理。还有个细节的问题需要确认一下，如果表头带有筛选项的时候，Popover 的出现时机是否要限制在鼠标或键盘聚焦于表头文本区域。
为什么有这个疑问呢，是因为无论表头筛选是否有 Tooltip 或 Popover 的时候，desc 的展现时机会比较模糊，特别是如果表头筛选项支持 Tooltip 或者 Popover 的时候。

**Comment by Phinome** [comment]
@Justineo 我重新思考了一下，修改了最新的设计：单纯提供一个 `desc` 属性用于实现对表头做额外内容补充的 `Popover` 展现，可能有点不太全面。实际应用中，大部分场景下，还需要定义 `Popover` 组件的位置和消失时间，甚至是 `class`，因此，将 `Popover` 组件的这些配置属性都开放出来，可以解决大部分场景下，使用配置而不是自定义 `slots` 来实现表头的额外说明。

基于我上面这个思路的组件，我已经实现完毕。

---

想听听你的看法~

**Comment by Justineo** [comment]
开放和封闭是两种思路。如果我们的目标是约束交互，那么开放出去的配置就应该控制在比较小的范围，大多数的行为都是我们预先设计好的。像位置、消失时间这类的，我理解设计上本身就已经有了自己的考量，总体上我更倾向于暴露比较少的配置，等到使用方有实际的自定义需求了再考虑是否开放出去。

**Comment by Phinome** [comment]
嗯嗯，愉快的达成共识~
![image](https://user-images.githubusercontent.com/1940194/99669159-a326ca00-2aa9-11eb-892c-3420fbcec5bb.png)

**Comment by Justineo** [comment]
Implemented in #749.
