### ISSUE TITLE
给组件增加文案定制的 API

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#750]
1. 每个组件在业务场景下可能需要不同的文案，如对话框的“确定”、“取消”在某些场景下可能需要使用的是“提交”、“放弃”等话术，添加标签按钮可能使用“新建选项”；
2. 不排除有全局定义某个组件某处文案的场景。

所以需要设计如何来来支持这个需求。比较简单的方式就是每个场景都开一个 prop，比如对于 Dialog，新增两个 prop 分别自定义“确定”、“取消”的文本。比如 Ant Design 的 Modal 组件就有 `okText`、`cancelText` 两个 prop。

---

梳理一下 VEUI 里面目前可能需要定制的文案（和 i18n 支持的文案基本一致，需要考虑一下仅辅助设备可见的文本是否需要支持）：

| 组件 | 文案 | 设计<sup>（目前仅开放一部分单独可配）</sup> |
| -- | -- | -- |
| AlertBox | 知道了 | `ok-label` |
| Dialog / ConfirmBox / PromptBox / Drawer | 确定 \| 取消 | `ok-label` \| `cancel-label` |
| Dropdown | 无搜索结果 | - |
| FilterPanel | 没有数据 | - |
| Pagination | 确定 | - |
| Select | 无搜索结果 | - |
| Table | 没有数据 \| 数据加载中… | - |
| Tabs | 添加 |  `add-label` |
| Transfer | 待选项 \| 已选项 \| 全选 \| 清空 \| 没有待选项 \| 请选择 | `candidate-title` \| `selected-title` \| - \| - \| - \| - |
| Uploader | 上传成功！ \| 上传失败 \| 上传中…… | - |

† 有一部分文案已经支持通过 `placeholder` 进行替换。

**Comment by Phinome** [comment]
1. 的确需要对带有操作按钮的组件提供通过 `prop` 或者 `slot` 方式定制按钮文案。
2.全局的配置，似乎没有必要，业务方可以自行定义全局引用，然后在具体的组件里通过 `prop` 传递具体的引用即可。

**Comment by Justineo** [comment]
> 2.全局的配置，似乎没有必要，业务方可以自行定义全局引用，然后在具体的组件里通过 `prop` 传递具体的引用即可。

这样就需要每个组件实例上都要自定义了。

**Comment by liuniansilence** [comment]
Dialog可以添加props来定制按钮的文案，如上所说的antd里的okText、cancelText这种prop；
