### ISSUE TITLE
Tabs list 样式设置 z-index: 1 是为啥

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#765]
https://github.com/ecomfe/veui/blob/f4c12fe81e9948e0b88a55cbb64ece194bd168e6/packages/veui-theme-dls/components/tabs.less#L31

**Comment by Justineo** [comment]
貌似不必要，把下面的 `after` 改成 `before` 应该就能删了。

https://github.com/ecomfe/veui/blob/f4c12fe81e9948e0b88a55cbb64ece194bd168e6/packages/veui-theme-dls/components/tabs.less#L17

https://github.com/ecomfe/veui/blob/f4c12fe81e9948e0b88a55cbb64ece194bd168e6/packages/veui-theme-dls/components/tabs.less#L290

https://github.com/ecomfe/veui/blob/f4c12fe81e9948e0b88a55cbb64ece194bd168e6/packages/veui-theme-dls/components/tabs.less#L332
