### ISSUE TITLE
overlay 组件 afterclose 事件没有触发

### ISSUE THREAD

**Issue by Clovis0070** [ecomfe/veui#794]
![image](https://user-images.githubusercontent.com/25895886/108984767-426fe480-76cb-11eb-94db-49b8f03bf75e.png)
open = false 后，afterclose事件的回调没有触发

**Comment by fuchunhui** [comment]
no problems found.
![2021-03-09 15 09 53](https://user-images.githubusercontent.com/29879262/110432256-d6897500-80e9-11eb-8331-e4e5ef37c6b8.gif)
![demo1](https://user-images.githubusercontent.com/29879262/110432288-dd17ec80-80e9-11eb-846e-5a7d41bd44a0.png)
![demo2](https://user-images.githubusercontent.com/29879262/110432297-e0ab7380-80e9-11eb-9504-3272400a37cc.png)
没发现问题，请再检查下是否自身逻辑问题。

**Comment by Justineo** [comment]
@fuchunhui 他这个应该是没有用 transition 的场景，现在 @afterclose 是在 transition 结束才抛出的。

**Comment by 599316527** [comment]
![image](https://user-images.githubusercontent.com/1331413/110905242-24e68000-8345-11eb-8ecd-4969b5026202.png)

上次好像给你报过这个问题

**Comment by xiaodemen** [comment]
@Clovis0070 没有复现，请补充下复现步骤。

**Comment by Justineo** [comment]
Already fixed.
