### ISSUE TITLE
Dialog属性只能控制 “确定”按钮是否 loading ，无法控制 disabled

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#805]
如题，实际使用时往往因为要有 disabled 状态而整个 `v-slot:foot`。

希望增加 `disabled` 属性 或改为 支持 `normal | loading | disabled` 的枚举字段

**Comment by Justineo** [comment]
`disabled` 状态预期是不是只禁用“确定”按钮？

**Comment by 599316527** [comment]
是的
