### ISSUE TITLE
SearchBox显示suggestions时，回车不能触发搜索

### ISSUE THREAD

**Issue by Clovis0070** [ecomfe/veui#806]
![image](https://user-images.githubusercontent.com/25895886/114996395-5ff24b00-9ed1-11eb-8267-264800655dd5.png)
直接按回车没有触发搜索。

**Comment by 599316527** [comment]
版本，调用方法，复现步骤...

**Comment by Clovis0070** [comment]
版本：2.0.0-beta.27
问题组件：SearchBox
问题具体描述：
searchbox输入值，没有suggestions时，按回车可以正常使用
如果给组件设置 suggestion，在搜索栏输入值后，显示suggestions，此时按回车不会触发搜索。必须点选其中一项后回车键才能触发搜索。
![image](https://user-images.githubusercontent.com/25895886/115850796-d1457700-a458-11eb-867f-5b7b9b98f06a.png)
