### ISSUE TITLE
Steps 组件接口

### ISSUE THREAD

**Issue by Domy** [ecomfe/veui#81]
# Steps Props

| prop | type | default | desc |
| --- | --- | --- | --- |
| direction | String | horizontal | 显示方向，可选值：vertical、horizontal |
| timeline | Boolean | false | 时间线样式，可选值：true、false |

# Steps.Step Props

| prop | type | default | desc |
| --- | --- | --- | --- |
| title | String | - | 标题 |
| icon | String | - | 图标 |
| description | String | - | 描述 |

# usage
```html
<veui-steps>
  <veui-step title="第一步" />
  <veui-step title="第二步" />
  <veui-step title="第三步" />
</veui-steps>
```

**Comment by Justineo** [comment]
`Step` 的内容应该是有规律的，建议给一个 `steps` 的数组 prop，然后循环输出，还是不要整体用 slot 比较好。之前 `Tabs` 分开我理解是因为每一项内容都不一样，每个要在 scoped slots 里面区分书写很麻烦。`Steps` 建议就给每个 item 开放一个统一的 scoped slot，循环输出来搞。

比如 `steps` 里面可能是：

```js
[
  { label: 'Step 1', desc: '填写信息' },
  { label: 'Step 2', desc: '验证身份' },
  { label: 'Step 3', desc: '注册成功' }
]
```

Steps 组件里面默认的 scoped slot 这样写：

```vue
<slot v-for="step in steps" v-bind="step">
  <h3>{{ step.label }}</h3>
</slot>
```

用起来可以是：

```vue
<veui-steps :steps="steps" :current="step">
  <template scope="step">
    <!-- 扩展 scoped slot -->
    <h3>{{ step.label }}</h3> <!-- 默认支持的数据 -->
    <p>{{ step.label }}</p> <!-- 默认支持的数据 -->
    <p><icon :name="getIcon(step.status)"</p> <!-- 自定义数据 -->
  </template>
</veui-steps>
```
