### ISSUE TITLE
建议SearchBox组件suggestion增加高度限制

### ISSUE THREAD

**Issue by Clovis0070** [ecomfe/veui#823]
版本：2.0.0-beta.27
问题描述：SearchBox组件，suggestions赋值20条数据，发现建议文本展示在搜索框上方，并且很多条目超出屏幕无法点击。
![image](https://user-images.githubusercontent.com/25895886/116345022-e84de580-a819-11eb-8a20-9579fd14efbb.png)

建议：给建议文本的容器增加一个高度限制，超出高度的部分滚动展示。

**Comment by Justineo** [comment]
Fixed in #826.
