### ISSUE TITLE
Context 接口设计

### ISSUE THREAD

**Issue by xiaodemen** [ecomfe/veui#827]
# createContext
- 签名：`(displayName?: string) => Context` // { Provider, Consumer, useConsumer }
- 创建`Context`，其中包括 `Provider` 用来生产 context，`useConsumer` 是一个 `mixin factory` 用来生成 mixin 向消 
 - `Provider`/`Consumer` 不用介绍了
 - 因为 `VEUI` 中有些配置不是props，需要使用 mixin 来注入，所以提供 `useConsumer` 向消费方组件注入 context。

# Provider 组件

## Props
prop | type | default | desc
-----|------|--------|------
value | any |  - | context 的值

# Consumer 组件
- scopedSlot.default(contextValue)

# useConsumer
```ts
// 将 context 值注入到 `consumerVm[inject]`

function useConsumer(inject: string): Mixin;
```

## demo
```vue
// 参考 React 的设计
const MyContext = createContext('my-context')

<MyContext.Provider :value="{foo: 200}">
  <MyContext.Consumer>
      <template #default="context">{{ context.foo }}</template>
  </MyContext.Consumer>
</MyContext.Provider>

// Mixin 用法
defineComponent({
  name: 'veui-demo',
  mixins: [MyContext.useConsumer('context')],
  created() {
   this.context // {foo: 1} 响应式
  }
})

// 目前会暴露全局配置 Context
import { Context, AlertBox } from 'veui'

<Context.Provider :value="{'alertbox.priority': 200}">
  <veui-alert-box>恭喜你</veui-alert-box> // 其中实现使用了 Context.useConsumer
</Context.Provider>

// 之后可进一步支持 composition API：useContext(MyContext)
```

**Comment by 599316527** [comment]
这个是为了解决目前 config 无法多实例隔离的问题吗？

**Comment by xiaodemen** [comment]
无法支持 `ConfigProvider` 的配置项：
- `overlay.baseZIndex`
- `longpress.xxx`
- `nudge.xxx`
- `tooltip.warmup`/`tooltip.cooldown`

**Comment by 599316527** [comment]
Dialog 底部按钮文案之类的是不是也可以通过 CongifProvider 来进行重写，这样组件也就不需要暴露过多 props。

```
<Dialog okLabel="保存">...</Dialog>
```

```
<Context.Provider :value="{'dialog.ok': '保存'}">
     <Dialog>...</Dialog>
</Context.Provider>
```

**Comment by Justineo** [comment]
应该是可以的。不过专门给实例创建一个 Provider 我感觉不如直接提供一个 prop……

**Comment by 599316527** [comment]
就实现来说，提供 props 得一个组件一个组件地改（就算有个mixins统一处理也得修改每个组件加上这个mixins）；而 Provider 跟配置打通了，所有的组件都生效。

对使用来说，其实差不多。甚至如果是复用场景的话，可能 Context 更好一点。

```
<Context.Provider :value="{'dialog.ok': '保存'}">
     <ResizeableDialog>
         在 Dialog 基础上自己封装的可拖动改变大小的Dialog
         通过 Context 由使用方修改 dialog 内部配置，而不需要封装的组件透传参数
     </ResizeableDialog>
</Context.Provider>
```
