### ISSUE TITLE
Dropdown not support setting the 'ui' attribute to strong

### ISSUE THREAD

**Issue by myth929** [ecomfe/veui#851]
version: 2.0.0-rc.3
description: Use dropdown as the extension button of the button group. Hope to support all the 'ui' attribute of the button.
example:
![image](https://user-images.githubusercontent.com/26782619/124556492-ebdd9880-de6a-11eb-9f4a-6075b188c238.png)

**Comment by Justineo** [comment]
It's reverted in the latest version. Current design spec doesn't include `strong` for Dropdown's `ui` prop.
