### ISSUE TITLE
$toast.success接口行为与文档不符，不支持 options 参数

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#861]
![image](https://user-images.githubusercontent.com/1331413/126952429-53ae6594-fc5d-4180-b622-840472547a58.png)

https://github.com/ecomfe/veui/blob/19099715b206830eb1a65c1190bd448e97480be4/packages/veui/src/managers/toast.js#L65-L67

**Comment by xiaodemen** [comment]
#863 fixes

**Comment by Justineo** [comment]
Fixed by #864.
