### ISSUE TITLE
Uploader 组件单文件模式可能显示两个文件

### ISSUE THREAD

**Issue by Clovis0070** [ecomfe/veui#866]
版本：2.0.1
问题：Uploader组件multiple=false,max-num=1的单文件模式下，先上传失败一次，然后手动修改value数据，会看到失败的框和新添加的文件同时存在。
![image](https://user-images.githubusercontent.com/25895886/127304168-f2a44fea-bd02-4c0e-803c-c679e81a91df.png)

**Comment by Justineo** [comment]
手动修改 `value` 数据是怎么修改的？

**Comment by Clovis0070** [comment]
> 手动修改 `value` 数据是怎么修改的？

外部使用uploader组件时绑定了value字段，然后外部给 value 字段赋值，赋值前后 value 的值都是 object 不是 array。

**Comment by Justineo** [comment]
你可以给一个最小可以复现这个问题的代码示例，以后报告 bug 请尽量减少模糊的描述性语言，用更高效率的方式来表达。

**Comment by Clovis0070** [comment]
https://codepen.io/clovisRubin/pen/poPVeYN 这个有一个示例，上传后会显示错误，然后点 setValue 按钮就可以复现问题了

**Comment by Justineo** [comment]
Fixed by #867.
