### ISSUE TITLE
Can INPUT support 'trim'

### ISSUE THREAD

**Issue by myth929** [ecomfe/veui#874]
### 新功能详情

In most cases, the value of INPUT does not need a space at two sides. Can 'trim' be used as an exposed attribute of INPUT?

**Comment by Justineo** [comment]
[Preview](https://veui-git-input-trim-ecomfe.vercel.app/input#:~:text=%E7%A7%BB%E9%99%A4%E5%89%8D%E5%90%8E%E7%A9%BA%E7%99%BD)

**Comment by myth929** [comment]
'trim'触发时机是否应该在确定输入或者'input'失焦时，现在无法输入中间含有空格的字符串，比如：『a b c』

**Comment by Justineo** [comment]
的确，需要修改一下。不过还有一个需要考虑的问题是直接通过按 <kdb>enter</kbd> 也是可能直接触发表单提交而不先触发 `change` 事件的。
