### ISSUE TITLE
意外触发的 Click 事件，导致与 OneUI Drawer 的兼容性问题

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#878]
### 版本信息

```sh
略
```

### 问题详情

当页面存在 OneUI 组件 `<Drawer closeDrawerByClickBody></Drawer>` 且已打开时，初始化包含 veui 的代码，会导致已打开的 Drawer 关闭。

原因是 Drawer 会监听 window `click` 事件触发关闭，而 veui 初始化时会触发一个 click 事件。

![image](https://user-images.githubusercontent.com/1331413/130259671-7a319dd2-7e29-4509-80eb-a87923cb590e.png)

https://github.com/ecomfe/veui/blob/c3cc9a32c629c7f2650e65926debb5367ee6c2e5/packages/veui/src/utils/dom.js#L37

### 问题复现

略

**Comment by Justineo** [comment]
Fixed.
