### ISSUE TITLE
Tooltip组件的target，支持应该包括Object类型

### ISSUE THREAD

**Issue by teazean** [ecomfe/veui#91]
如果一个target[ref]是在v-for循环里面，target的值只能是数组，可以在当前vm提前获取target的HTMLElement，传给Tooltip，但到Tooltip会抛warning.

```
[Vue warn]: Invalid prop: type check failed for prop "target". Expected String, got HTMLDivElement.
```

**Comment by teazean** [comment]
目前除了prop抛warning，其他的都能正常工作

**Comment by Justineo** [comment]
数组会处理取第一项的吧，所以应该不需要支持提前获取。只要保证 `ref` 唯一就可以了。

**Comment by teazean** [comment]
ref 在v-for里面是个数组。。唯一不了.

默认取第一个值，还是实现不了，除非在传入一个refIndex的属性。
