### ISSUE TITLE
Syntax Error: TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by danielmlc** [ecomfe/veui#927]
### 版本信息

```sh
"veui": "^2.2.0",
"veui-theme-dls": "^2.2.0",
"vue": "^2.6.11"
```

### 问题详情

![image](https://user-images.githubusercontent.com/16604995/140312959-9b4c28d3-1b2c-4da9-a2da-85e38ba22ace.png)
引入组件后报错！按照readme文档要求配置了！

### 问题复现

用@vue-cli搭建项目可复现此问题

**Comment by Justineo** [comment]
无法复现，请确认使用了新版本的 Vue CLI。你可以提供一个 GitHub repo 作为复现。

**Comment by danielmlc** [comment]
"@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",

**Comment by danielmlc** [comment]
用的是这个这个版本的 有没有上手的demo  这个匹配起来很难跑起来

**Comment by danielmlc** [comment]
[Uploading veui-demo.zip…]()

**Comment by danielmlc** [comment]
我上传了一个示例 能帮忙看下问题吗

**Comment by Justineo** [comment]
你没有上传成功……不要传打包的文件吧，你开一个新的 GitHub repo，然后把你初始化完的项目提交上去，我来看一下。

**Comment by danielmlc** [comment]
https://github.com/danielmlc/veui-demo
麻烦看下

**Comment by Justineo** [comment]
https://veui.dev/getting-started#webpack-loader

**Comment by danielmlc** [comment]
抱歉，我按照那个配置以后 重新下了包还是一样的错误，改完的代码我重新上传了

**Comment by danielmlc** [comment]
v

**Comment by danielmlc** [comment]
https://github.com/danielmlc/veui-demo

**Comment by Justineo** [comment]
> 我按照那个配置以后

并没有，我看到你的配置还是和文档里不一样。你直接复制文档里的吧……

```diff
@@ -2,7 +2,9 @@
   css: {
     loaderOptions: {
       less: {
-        javascriptEnabled: true,
+        lessOptions: {
+          javascriptEnabled: true
+        }
       }
     }
   },
```

**Comment by danielmlc** [comment]
我把文档的粘贴过来了 还是报错 是不是不是这里的问题呢？  babel 和webpack的都按要求配置了 无解了

**Comment by danielmlc** [comment]
module.exports = {
  css: {
    loaderOptions: {
      less: {
        lessOptions: {
          javascriptEnabled: true
        }
      }
    }
  },
  transpileDependencies: ['veui'],
  chainWebpack (config) {
    config.module
      .rule('veui')
      .test(/\.vue$/)
      .pre()
      .use('veui-loader')
      .loader('veui-loader')
      .tap(() => {
        return {
          modules: [
            {
              package: 'veui-theme-dls',
              fileName: '{module}.less'
            },
            {
              package: 'veui-theme-dls',
              fileName: '{module}.js',
              transform: false
            }
          ]
        }
      })
  }
}

**Comment by danielmlc** [comment]
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  plugins: [
    'veui',
    'lodash'
  ]
}

**Comment by danielmlc** [comment]
![image](https://user-images.githubusercontent.com/16604995/140505293-09acb6c2-be80-4ee9-b6a2-ac6dfc2e2691.png)
一直是这个错

**Comment by danielmlc** [comment]
代码我又又上传了  抱歉了

**Comment by danielmlc** [comment]
你可以跑一下试试

**Comment by Justineo** [comment]
我知道了，你应该是用的 `@vue/cli@4` 创建的项目，依赖的是 `webpack@4`。`less-loader@8` 开始就只支持 `webpack@5` 了。你可以下面二选一试一下：

1. `npm i -g @vue/cli@next` 以后重新初始化，并按文档操作；
2. 安装 `less-loader` 的时候指定 `npm i -D less-loader@7`。

**Comment by danielmlc** [comment]
确实这样。谢谢
