### ISSUE TITLE
引入import 'veui-theme-dls-icons' 项目报错

### ISSUE THREAD

**Issue by danielmlc** [ecomfe/veui#929]
### 版本信息

```sh
+-- veui@2.2.1 
`-- vue@2.6.14
```

### 问题详情

Syntax Error:

      .@{veui-prefix}-icon {
        transform: translateX(percentage(-(sqrt(2) - 1) / 2) / 2);
                            ^
Error evaluating function `percentage`: argument must be a number
      Error in E:\project\component\vue-demo\node_modules\veui-theme-dls\components\lightbox.less (line 152, column 30)

 error  in ./node_modules/veui-theme-dls/components/popover.less?vue&type=style&index=0&lang=less&

Syntax Error:

    @arrow-offset: @arrow-indent - @arrow-size / 2;
  ^
Operation on an invalid type
      Error in E:\project\component\vue-demo\node_modules\veui-theme-dls\components\popover.less (line 18, column 4)

 error  in ./node_modules/veui-theme-dls/components/tooltip.less?vue&type=style&index=0&lang=less&

Syntax Error:

  @arrow-indent: @dls-tooltip-arrow-spacing;
  @gap: @dls-tooltip-target-spacing + @arrow-size / 2;
^
Operation on an invalid type
      Error in E:\project\component\vue-demo\node_modules\veui-theme-dls\components\tooltip.less (line 7, column 2)

### 问题复现

参考项目

**Comment by danielmlc** [comment]
https://github.com/danielmlc/veui-demo

**Comment by Justineo** [comment]
> https://github.com/danielmlc/veui-demo

404 了

**Comment by danielmlc** [comment]
https://github.com/danielmlc/veui-demo 
可以啊

**Comment by Justineo** [comment]
说明你把它设置成 `private` 了吧。

**Comment by danielmlc** [comment]
还是是上次的项目，引入主题库就报错。 仓库现在能访问了

**Comment by Justineo** [comment]
`npm i -D less@3`

---

这个我们疏忽了，Less 4 有 breaking change，我们还没有做兼容，可以先用 v3。
