### ISSUE TITLE
v-drag的调用配置handle后，如果拖拽后handle重新渲染会丢失drag之前事件监听

### ISSUE THREAD

**Issue by liuniansilence** [ecomfe/veui#962]
### 版本信息

```sh
vue@2.6.14
veui@2.3.4
```

### 问题详情

v-drag的时候配置了handle属性，handle指定的是列表项内的一个icon的HtmlElement。拖拽列表项后，列表项按照预期要做重新渲染，渲染后的icon也是得到的新的。之前绑定在icon上的事件监听貌似就丢了。具体表现是：第一次drag操作可以work，接下来的拖拽就无法进行了，鼠标hover也不变成小手的鼠标样式了，怀疑icon上的事件丢失。

问题复现只提供了大概的template的demo。

### 问题复现

https://codepen.io/Leo-Hou/pen/XWeVdWr

**Comment by Justineo** [comment]
元素重新渲染以后指令会被销毁，本质上属于无法处理拖拽过程中被拖拽元素被 Vue 重新渲染的情况。
