### ISSUE TITLE
Tab v-if 切换出现诡异的现象

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#969]
### 版本信息

```sh
* veui 2.4.2
* veui-theme-dls 2.4.2
* vue 3.2.26
```

### 问题详情

1. `v-if` 移除/渲染 Tab 后 active 值不符合预期
2. `v-if` 移除/渲染 Tab 后 Tab 顺序不符合预期

https://user-images.githubusercontent.com/1331413/148729092-8bb96d85-971f-4564-ac00-7aa8b022ca7c.mov

### 问题复现

https://codesandbox.io/s/veui-tabs-dynamic-tab-mhl7p?file=/src/Demo.vue

**Comment by Justineo** [comment]
Fixed in #972.
