### ISSUE TITLE
veui-uploader disabled 状态下 预览图 没有显示

### ISSUE THREAD

**Issue by markfan** [ecomfe/veui#971]
### 版本信息

```sh
veui@2.3.4 deduped
  │ └── vue@2.6.14 deduped
```

### 问题详情

veui-uploader disabled 状态下 预览图 没有显示
![image](https://user-images.githubusercontent.com/2517143/148920868-3201e50c-c59d-46b8-8eb9-1514d33e6def.png)

### 问题复现

https://codepen.io/Justineo/pen/yLbxxOR

**Comment by Justineo** [comment]
> https://codepen.io/Justineo/pen/yLbxxOR

这个只是个初始的复现模板……

**Comment by Justineo** [comment]
Fixed.
